### ISSUE TITLE
cannot list poddisruptionbudgets.policy at the cluster scope

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#104]
Hi , I saw the error logs from  `mpi-operator-5cdb797cd-btdg8` pod, what this means?

```
k8s.io/client-go/informers/factory.go:132: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:mpi-operator:mpi-operator" cannot list poddisruptionbudgets.policy at the cluster scope

```

**Comment by terrytangyuan** [comment]
We recently added support for gang scheduling which requires pdb. See the updated rbac roles here: https://github.com/kubeflow/mpi-operator/blob/master/deploy/2-rbac.yaml

**Comment by tingweiwu** [comment]
@terrytangyuan ok, I got it.  refresh the rbac solved the error. close this.
