### ISSUE TITLE
v1alpha2 does not work.

### ISSUE THREAD

**Issue by Akado2009** [kubeflow/mpi-operator#121]
I  deployed a crd tiwtce (one from kubeflow registry using ksonnet, another from your deploy folder) and both time, when I try to submit v1alpha2 yaml I got the same error:
```
No match for kind "MPIJob" in "kubeflow/v1alpha2".
```
Am I doing something wrong? All yaml files are provided in your repository.

**Comment by rongou** [comment]
v1apha2 is still a work in progress. @terrytangyuan

**Comment by terrytangyuan** [comment]
Yes still work in progress. @fisherxu has been helping with that. @fisherxu Could you share an update with us here?

**Comment by fisherxu** [comment]
@Akado2009 Do you have created the crd before create the cr？Deploy through ksonnet haven't been updated, will updated later.  You can deploy from our deploy folder, maybe need build a v1alpha2 image first:)

**Comment by Akado2009** [comment]
@terrytangyuan  @rongou  @fisherxu  thank you for the information! Looking ofrward to you finishing that one.

We'd better stick to v1alpha1 now, since we don't wanna depend on custom built iamges and all :)

**Comment by terrytangyuan** [comment]
Closing this now since v1alpha2 is ready
