### ISSUE TITLE
undefined: serializer.DirectCodecFactory

### ISSUE THREAD

**Issue by toyow** [kubeflow/mpi-operator#144]
# github.com/kubeflow/mpi-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2
/data/go/pkg/mod/github.com/kubeflow/mpi-operator@v0.2.1/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/kubeflow_client.go:72:32: undefined: serializer.DirectCodecFactory

**Comment by terrytangyuan** [comment]
Closing since there is not description for this issue
