### ISSUE TITLE
must validate one and only one schema (oneOf)     /v1alpha1

### ISSUE THREAD

**Issue by toyow** [kubeflow/mpi-operator#150]
when I use  
"github.com/kubeflow/mpi-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha1"
to create  mpijob in k8s cluster  ，this problem occurs。

**Comment by gaocegege** [comment]
Can you show us more info about your problem and the version you used?

**Comment by toyow** [comment]
the pkg I use:

"github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha1
kubeflowv1alpha1   "github.com/kubeflow/mpi-operator/pkg/client/clientset/versioned/typed/kubeflow/v1alpha1"
corev1    "k8s.io/api/core/v1"
metav1   "k8s.io/apimachinery/pkg/apis/meta/v1"
the code:

func InitMPIJob(jobArgs *model.JobConfig) {
	if mpiJobClient != nil && jobArgs.Namespace == mpiNamespace {
		return
	}
	mpiNamespace = jobArgs.Namespace
	dir, _ := filepath.Abs(`.`)
	kubeconfig := dir + "/config_aliyun_" + jobArgs.Env
	config, _ := clientcmd.BuildConfigFromFlags("", kubeconfig)
	// create the workflow client
	mpiJobClient = kubeflowv1alpha1.NewForConfigOrDie(config).MPIJobs(mpiNamespace)
	mpiKubeClient = kubernetes.NewForConfigOrDie(config)
}

func BuildMPIJob()  {
	var backoffLimit int32 = 1
	GPUs := int32(1)
	Replicas := int32(1)
	mpiJob_v1 := v1alpha1.MPIJob{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kubeflow.org/v1alpha1",
			Kind:       "MPIJob",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "mpi-test",
		},
		Spec: v1alpha1.MPIJobSpec{
			GPUs:         &GPUs,
			BackoffLimit: &backoffLimit,
			Replicas:     &Replicas,
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Name: "mpi-test",
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:    "mpi-test",
							Image:   "ubuntu",
							Command: []string{"/bin/sh"},
							Args:    []string{"-c", "echo hello;sleep 5;echo hello"},
						},
					},
				},
			},
		},
	}

	mpiJobClient.Create(&mpiJob_v1)
}

**Comment by gaocegege** [comment]
Are you using v1alpha1?

**Comment by toyow** [comment]
> Are you using v1alpha1?

yes

**Comment by gaocegege** [comment]
We deprecate v1alpha1 now, could you have a try on v1alpha2?

**Comment by toyow** [comment]
> We deprecate v1alpha1 now, could you have a try on v1alpha2?

the  command line  edition   of arena  only support   v1alpha1。And we want to submit mpijob   through  both  command line  edition  and  client edition。May I have some suggestions？

[词典] | command line
-- | --

**Comment by gaocegege** [comment]
Maybe you could remove the validation fields here https://github.com/kubeflow/mpi-operator/pull/136/files#diff-ee2d3a62b179947920852d440f7c4febL16

**Comment by toyow** [comment]
I get it 。
description: Only one of `gpus`, `processingUnits`, or `replicas` should be specified。
I set the  gpus and the  replicas   number  at  the  same time。
Thanks a lot ！

**Comment by gaocegege** [comment]
Yeah, it is an error from OpenAPI schema validation. There are two ways to fix:

- Remove the validation or
- Fix spec according to the validation error.

/close
