### ISSUE TITLE
Can't run MPIJob on Openshift 4.1 with MPI-Operator

### ISSUE THREAD

**Issue by vtlrazin** [kubeflow/mpi-operator#151]
I deployed mpi-operator on OpenShift 4.1.

After run TF benchmark job I got error:

I1030 13:02:12.640881       1 mpi_job_controller.go:432] Finished syncing job "default/tensorflow-benchmarks" (4.527261ms)
E1030 13:02:12.640916       1 mpi_job_controller.go:419] error syncing 'default/tensorflow-benchmarks': configmaps "tensorflow-benchmarks-config" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>

job deployed successfully:

# oc  get mpijobs tensorflow-benchmarks -o yaml
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeflow.org/v1alpha2","kind":"MPIJob","metadata":{"annotations":{},"name":"tensorflow-benchmarks","namespace":"default"},"spec":{"cleanPodPolicy":"Running","mpiReplicaSpecs":{"Launcher":{"replicas":1,"template":{"spec":{"containers":[{"command":["mpirun","--allow-run-as-root","-np","2","-bind-to","none","-map-by","slot","-x","NCCL_DEBUG=INFO","-x","LD_LIBRARY_PATH","-x","PATH","-mca","pml","ob1","-mca","btl","^openib","python","scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py","--model=resnet101","--batch_size=64","--variable_update=horovod"],"image":"mpioperator/tensorflow-benchmarks:latest","name":"tensorflow-benchmarks"}]}}},"Worker":{"replicas":2,"template":{"spec":{"containers":[{"image":"mpioperator/tensorflow-benchmarks:latest","name":"tensorflow-benchmarks","resources":{"limits":{"nvidia.com/gpu":1}}}]}}}},"slotsPerWorker":1}}
  creationTimestamp: "2019-10-30T13:02:12Z"
  generation: 1
  name: tensorflow-benchmarks
  namespace: default
  resourceVersion: "475237"
  selfLink: /apis/kubeflow.org/v1alpha2/namespaces/default/mpijobs/tensorflow-benchmarks
  uid: 7d43b8da-fb15-11e9-9f8a-000c29820f6c
spec:
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "2"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
            - --model=resnet101
            - --batch_size=64
            - --variable_update=horovod
            image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
            resources:
              limits:
                nvidia.com/gpu: 1
  slotsPerWorker: 1

**Comment by pdmack** [comment]
On OpenShift, the mpi-operator clusterrole requires a finalizers resource to be explicitly declared in the kubeflow.org API group:
```
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - mpijobs/finalizers
  - mpijobs/status
```

**Comment by vtlrazin** [comment]
Thanks Pete,

I added and tested.
It works now!

May we need add this line to our deployment YAML file?
B.R.
Vitaliy

**Comment by pdmack** [comment]
Requires proper fixes in this upstream. Be advised that you will run into a similar issue with the notebooks and the distributed training ClusterRoles. But at least you will understand it a little better. :-)

**Comment by vtlrazin** [comment]
Added pull request.
