### ISSUE TITLE
Installation instructions should use kustomize not ksonnet

### ISSUE THREAD

**Issue by jlewi** [kubeflow/mpi-operator#157]
The readme and website docs still refer to ksonnet to install the mpi-operator

https://www.kubeflow.org/docs/components/training/mpi/
https://github.com/kubeflow/mpi-operator

We should have a kustomize package here
https://github.com/kubeflow/manifests/tree/master/mpi-job/mpi-operator

Can we update the docs to explain how to install using kustomize?

**Comment by terrytangyuan** [comment]
Yes we should update the docs to reflect that. @stpabhi Would you like to submit a PR to update that?

**Comment by stpabhi** [comment]
@terrytangyuan Done. #158 https://github.com/kubeflow/website/pull/1447

**Comment by jlewi** [comment]
looks like the PR hasn't been merged yet. If you add

"Fix: kubeflow/mpi-operator:#157" as a comment on the PR the issue will be auto-closed once the PR is merged.
