### ISSUE TITLE
kubectl-delivery container port

### ISSUE THREAD

**Issue by hyoseon-agile** [kubeflow/mpi-operator#191]
Hi guys,
I wanna specify the port of kubectl-delivery container.
Can you tell me how to specify it?

**Comment by terrytangyuan** [comment]
It’s a init container as part of launcher pod if that’s what you are looking for. Is there any context of why you want to specify the port of that container?

**Comment by tenzen-y** [comment]
The kubectl-delivery was removed in MPIJob v2.
/close
