### ISSUE TITLE
[v1] launcher can also run the workload

### ISSUE THREAD

**Issue by carmark** [kubeflow/mpi-operator#197]

**Comment by alculquicondor** [comment]
Can you give some context on why was this necessary?

In my opinion, having the workload run in the launcher gives a less clear API. Sometimes you have N workers (where N is the number specified in the worker replicas) and sometimes you have N+1.

Another potential problem is that you don't have a fine control of how much of the requests/limits should go to the launcher process and how much to the workload process. If the idea is to be able to run a worker in the same node as the launcher, it can still be achieved by scheduling 2 pods on it (one for the worker and one for the launcher). Such behavior is more explicit from a user perspective.
