### ISSUE TITLE
Can't monitor mpijobs in all namespaces

### ISSUE THREAD

**Issue by junhuihuang** [kubeflow/mpi-operator#198]
Reproduce steps:
1. mpi-operator running configuration
    - env `KUBEFLOW_NAMESPACE` is not set
    - mpi-operator's running parameter `namespace` is not given
    - repo revision is `c72d677`
2. Test example
    - Modify file: `examples/v1alpha2/tensorflow-benchmarks.yaml`, adding `test` namespace
    - `kubectl create -f  examples/v1alpha2/tensorflow-benchmarks.yaml`
    - `kubernetes` don't create launcher job and statefulset workers, just created `tensorflow-benchmarks` mpijob
    - If remove `test` namespace from `tensorflow-benchmarks.yaml`, it works.

**Comment by terrytangyuan** [comment]
@junhuihuang Thanks! Related https://github.com/kubeflow/mpi-operator/pull/186#issuecomment-593557001

**Comment by terrytangyuan** [comment]
Un-assigning myself for now. Others feel free to pick this up and submit a fix.
