### ISSUE TITLE
Replace Launcher from v1.Job to v1.Pod

### ISSUE THREAD

**Issue by carmark** [kubeflow/mpi-operator#201]
We need to find the real job's status, not active number, since pending pod is a active job.

**Comment by gaocegege** [comment]
SGTM

**Comment by terrytangyuan** [comment]
Seems fine. cc @rongou to double check as well

**Comment by rongou** [comment]
I think the restart policy is useful for recovering from transient errors. Are you planning to implement similar logic in the controller?

**Comment by terrytangyuan** [comment]
Also, downstream apps may have been consuming from launcher job so we may need to be careful regarding compatibility. We probably want to make a release before merging the changes.

**Comment by carmark** [comment]
>I think the restart policy is useful for recovering from transient errors. Are you planning to implement similar logic in the controller?

**Comment by terrytangyuan** [comment]
@carmark I am fine with this change as long as the API keeps the same and restart policy is implemented (there are users who are already relying on this I think).

**Comment by carmark** [comment]
@terrytangyuan shall we add this issue for v1 graduation?

**Comment by terrytangyuan** [comment]
Sounds good to me.

**Comment by alculquicondor** [comment]
It doesn't look like restart policy was implemented, was it?

**Comment by terrytangyuan** [comment]
> It doesn't look like restart policy was implemented, was it?

No it's not implemented yet.

**Comment by alculquicondor** [comment]
I take that the only reason to move away from Job API was that active in k8s includes pending pods. Was this brought up to sig apps?

**Comment by terrytangyuan** [comment]
Yes, quoting from https://github.com/kubeflow/mpi-operator/issues/315#issuecomment-801604825:
> We need know the Pending/Running/Failed/Succeed status for the Pod
I don't think it's brought up to SIG Apps yet since none of us is involved in that SIG (others on this thread feel free to chime in and correct me if I am wrong).

**Comment by alculquicondor** [comment]
I'm asking upstream :)
