### ISSUE TITLE
are there any concerns to replace sshd with `kubectl exec` in MPI interaction?

### ISSUE THREAD

**Issue by cheyang** [kubeflow/mpi-operator#21]
When I read the design of MPI-operator, I noticed:

```
The launcher pod invokes mpirun and communicates with worker pods through MPI. The initial handshake is done through kubectl exec instead of SSH. 
```
Is there any concerns about performance which connects through API server? And if it's possible to use sshd for alternative solution?

**Comment by rongou** [comment]
Whether we use `ssh` or `kubectl exec`, it's only for the initial setup. The actually MPI communication is done through Open MPI's own sockets. In a typical deep learning environment it probably doesn't matter one way or the other.

On the other hand, if you are launching across thousands of gpus/nodes (e.g. on the Summit supercomputer), the latency of launching processes becomes a concern. In that case it's probably better to use PMIx (see #12).

Have you observed any performance issues with `kubectl exec`?

**Comment by cheyang** [comment]
Not yet, thanks for your response.
