### ISSUE TITLE
Prometheus Monitoring for mpi-operator

### ISSUE THREAD

**Issue by runzhliu** [kubeflow/mpi-operator#214]
Hi all, my team implemented an internal monitor based on [tf-operator](https://github.com/kubeflow/tf-operator/pull/1018) to collect some mpijobs metrics, I am wondering if we had any plan to do it in the official repo?

**Comment by terrytangyuan** [comment]
It would be great to add support for this so contribution is welcomed!

**Comment by terrytangyuan** [comment]
cc @johnugeorge  @gaocegege  @richardsliu @krishnadurai

**Comment by runzhliu** [comment]
See https://github.com/kubeflow/mpi-operator/pull/215
