### ISSUE TITLE
Graduate MPI Operator to v1

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/mpi-operator#217]
This issue tracks the progress of graduating MPI Operator to v1. Please check out the [application requirements](https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md) for details. Each item in the table below includes a check box that marks the completion of that particular requirement.

If you are interested in working on any of the items below, please leave a comment on this issue.

### Configuration and deployment

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] Kustomize package</li></ul>  | Required  | <ul><li>Kubeflow has standardized on Kustomize for configuring and deploying packages </ul> |
| <ul><li>- [x] Application CR</li></ul>  | Required  | <ul><li>Kubeflow has standardized on using the Kubernetes Application CR to provide consistent metadata and monitoring about applications <li> Application CR should be an owner of all resources so that deleting the application CR uninstalls the application </ul> |
| <ul><li>- [x] ```app.kubernetes.io``` labels on every resource</li></ul>  | Required  | <ul><li>Every resource that is part of the application should include the [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) recommended by Kubernetes, currently: <ul><li>`app.kubernetes.io/name` <li>`app.kubernetes.io/instance` <li>`app.kubernetes.io/version` <li>`app.kubernetes.io/component` <li>`app.kubernetes.io/part-of` <li>`app.kubernetes.io/managed-by`</ul> <li>See example [here](https://github.com/kubeflow/manifests/blob/v0.6.1/tf-training/tf-job-operator/overlays/application/application.yaml#L8-L13) </ul> |
| <ul><li>- [x] Images listed in kustomization.yaml</li></ul>  | Required  | <ul><li>All docker images used by the application should be listed in one or more kustomization.yaml files <li>This facilitates mirroring the images to different docker registries </ul> |
| <ul><li>- [x] Upgradeability</li></ul> | Required  | <ul><li>Applications must support upgrading between consecutive major and minor releases </ul> |
| <ul><li>- [ ] Separate cluster scoped and namespace scoped resources</li></ul> | Recommended  | <ul><li>To the extent possible cluster scoped resources should be installable separately (e.g. via a separate kustomize package) <li> This allows cluster admins to install only the cluster scoped resources <li> Clear documentation of cluster and namespace scoped behavior </ul> |
| <ul><li>- [x] Kustomize package should be deployable on its own</li></ul> | Recommended  | <ul><li>To the extent possible users should be able to run kustomize build | kubectl apply inside the kustomize package to deploy the application stand alone </ul> |

### Custom Resources

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] Version stability</li></ul> | Required  | <ul><li>No deprecative API changes </ul> |
| <ul><li>- [x] Multi Version Support</li></ul> | Required  | <ul><li>Serves multiple versions of the [CR per K8s docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions) </ul> |
| <ul><li>- [x] Supports status subresource</li></ul> | Required  | <ul><li>Status subresource documented [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource) </ul> |
| <ul><li>- [ ] CRD schema validation</li></ul> | Required  | <ul><li>Validation documented [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation) <li>Example: [TFJob](https://github.com/kubeflow/kubeflow/blob/v0.6.1/kubeflow/tf-training/tf-job-operator.libsonnet#L81) </ul> |
| <ul><li>- [x] Training operators follow kubeflow/common conventions </li></ul> | Required  | <ul><li>Conventions defined [here](https://github.com/kubeflow/common/blob/master/job_controller/api/v1/types.go) <li>Examples: [TFJob](https://github.com/kubeflow/kubeflow/blob/v0.6.1/kubeflow/tf-training/tf-job-operator.libsonnet) and [PyTorchJob](https://github.com/kubeflow/kubeflow/blob/v0.6.1/kubeflow/pytorch-job/pytorch-operator.libsonnet) </ul> |

### Logging and monitoring

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] Liveness/Readiness signals</li></ul> | Required  | <ul><li>The application should expose liveness and/or readiness signals as appropriate for the application </ul> |
| <ul><li>- [x] Prometheus metrics</li></ul> | Required  | <ul><li>Applications should export suitable application level metrics (e.g. number of jobs) using prometheus  </ul> |
| <ul><li>- [ ] Json logging</li></ul> | Recommended  | <ul><li>Applications should optionally emit structured logs with suitable metadata to facilitate debugging <li>e.g. CR controllers should annotate log messages with the name of the resource involved so it's easy to filter logs to all messages about a resource </ul> |

### Docker Images

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] Vulnerability Scanning</li></ul> | Required  | <ul><li>Docker images must be scanned for vulnerabilities and known vulnerabilities published </ul> |
| <ul><li>- [x] Licensing</li></ul> | Required  | <ul><li>Docker images must provide a list of all OSS licensces used by the image and its transitive dependencies, e.g. you can follow [these instructions](https://github.com/kubeflow/testing/tree/master/py/kubeflow/testing/go-license-tools) to get licenses of dependencies for Golang images </ul> |

### CI/CD

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [ ] E2E tests</li></ul> | Required  | <ul><li>E2E tests should be run on presubmit, postsubmit, and periodically <li> Tests should cover deployment (kustomize packages) <li> As well as the application functionality </ul> |
| <ul><li>- [ ] Scalability / load testing</li></ul> | Required  | <ul><li>Applications must have scalability and or load testing demonstrating that the application meets appropriate requirements for the application (e.g. # of concurrent CRs) </ul> |
| <ul><li>- [ ] Continuous building of docker images</li></ul> | Recommended  | <ul><li>On post-submit, docker images should be automatically built and pushed  </ul> |
| <ul><li>- [ ] Continuous updating of Kustomize manifests</li></ul> | Recommended  | <ul><li>On post-submit, kustomize packages should be automatically updated to point to latest images </ul> |

### Docs

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] API Reference docs</li></ul> | Required  | <ul><li>Applications exposing APIs (e.g. CRs) need reference docs documenting the API </ul> |
| <ul><li>- [x] Application docs</li></ul> | Required  | <ul><li>There must be docs on kubeflow.org explaining what an application is used for and how to use it </ul> |

### Ownership/Maintenance

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] Healthy number of committers and commits</li></ul> | Required  | <ul><li> Committers are listed as approvers in owners files <li> Number to be determined by TOC based on size and scope of application </ul> |
| <ul><li>- [x] At least 2 different organizations are committers</li></ul> | Required  | |

### Adoption

| Description | Category | Explanation |
|-------------|----------|-------------|
| <ul><li>- [x] List of users running the application</li></ul> | Recommended  | <ul><li>Suggest listing adopters willing to be identified publicly in ADOPTERS.md </ul> |

**Comment by NikeNano** [comment]
For the CI/CD part what type of infrastructure is expected/available? Are Github actions something that would be an option to pursue or what are we aiming for?

**Comment by terrytangyuan** [comment]
@NikeNano I think we can reuse https://github.com/kubeflow/testing.

**Comment by terrytangyuan** [comment]
I created separate issues with label "graduation" to track individual items that are currently being worked on in order to avoid duplicate efforts: https://github.com/kubeflow/mpi-operator/issues?q=is%3Aopen+is%3Aissue+label%3Agraduation

**Comment by alculquicondor** [comment]
I propose to add #360 as part of the requirements for v1, as part of the scalability needs.
