### ISSUE TITLE
Add support for MPICH 

### ISSUE THREAD

**Issue by junhuihuang** [kubeflow/mpi-operator#223]
How to schedule MPICH container using mpi-operator?

Thanks.

**Comment by terrytangyuan** [comment]
It's part of our [ROADMAP](https://github.com/kubeflow/mpi-operator/blob/master/ROADMAP.md) to decouple from OpenMPI and support other frameworks. I don't have any experience with MPICH though so contribution from the community is welcomed.

**Comment by junhuihuang** [comment]
OK, thanks your hard work.
