### ISSUE TITLE
Add E2E tests

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/mpi-operator#233]
Part of https://github.com/kubeflow/mpi-operator/issues/217. 

* E2E tests should be run on presubmit, postsubmit, and periodically
* Tests should cover deployment (kustomize packages) as well as the application functionality

**Comment by NikeNano** [comment]
I am looking in to this, but make not be super fast. Need to catch up on prow and the test infrastructure for Kubeflow work.

**Comment by terrytangyuan** [comment]
Thanks! Yes that’s correct.

**Comment by NikeNano** [comment]
I have played around with the test infra a bite. Do we have any thought about how we like the e2e test to look like? Should we build it based upon one of the examples? If so I suggest that we use the [v1alpha2/tensorflow-benchmark](https://github.com/kubeflow/mpi-operator/blob/master/examples/v1alpha2/tensorflow-benchmarks.yaml).

**Comment by terrytangyuan** [comment]
Yes that would be a good example to use for end2end test.

**Comment by terrytangyuan** [comment]
Actually v1 controller is the one we want to graduate so use this example instead: https://github.com/kubeflow/mpi-operator/blob/master/examples/v1/tensorflow-benchmarks.yaml

**Comment by naveensrinivasan** [comment]
@terrytangyuan  How about doing e2e using something like `k3d` or `kind`? This will give confidence for someone to run locally.  Similar to this https://github.com/kubeflow/kubeflow/pull/5400

**Comment by terrytangyuan** [comment]
See https://github.com/kubeflow/mpi-operator/issues/296 for an alternative approach to leverage AWS's test infra.

**Comment by terrytangyuan** [comment]
cc @Jeffwan @PatrickXYS @gaocegege

**Comment by terrytangyuan** [comment]
cc @kubeflow/wg-training-leads @PatrickXYS

**Comment by PatrickXYS** [comment]
FYI, you can check migration doc here https://github.com/kubeflow/testing/blob/master/aws/Doc/onboarding.md

**Comment by naveensrinivasan** [comment]
I agree that the end goal is  to use the real infrastructure. 


As a contributor I would like to run functional test prior submitting the PR.  Also I would like to run partial set of tests based on the changes. 

Can you explain what is the disadvantages of using something in memory and also have an option to use the actual infrastructure based on a flag?

This gives significant advantages of having a short dev/test cycle.

**Comment by naveensrinivasan** [comment]
> FYI, you can check migration doc here https://github.com/kubeflow/testing/blob/master/aws/Doc/onboarding.md

@PatrickXYS How do I get access to the repo? 

I would like to start working on the e2e tests.

**Comment by PatrickXYS** [comment]
> @PatrickXYS How do I get access to the repo aws-kf-ci-bot?

You won't, you should follow the doc to proceed

**Comment by alculquicondor** [comment]
I started to look into this (along with integration tests). Did anyone make any progress?
I'm thinking of using this package https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest

**Comment by alculquicondor** [comment]
With #399 and #403, I think we should be good to close this.

@terrytangyuan wdyt?

**Comment by terrytangyuan** [comment]
Sure
