### ISSUE TITLE
kubectl-delivery's Dockerfile fails in distroless

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/mpi-operator#254]
Thanks @audriusrudalevicius for bringing this up in https://github.com/kubeflow/mpi-operator/pull/196#discussion_r424325942.

Currently `cmd/kubectl-delivery/Dockerfile` has `ENTRYPOINT ["/bin/sh", "-c"]` which fails in distroless image: 

```
docker run -it --rm --entrypoint=/bin/sh gcr.io/distroless/base-debian10
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown.
```
Also cc @carmark

**Comment by rongou** [comment]
Actually the build itself is failing on docker hub: https://hub.docker.com/repository/registry-1.docker.io/mpioperator/kubectl-delivery/builds/95d784bf-c540-40fe-a5bb-6438176be6a7

**Comment by terrytangyuan** [comment]
@rongou Would it be a problem of running builds on your fork rongou/mpi-operator? Building it locally seems successful.

**Comment by terrytangyuan** [comment]
The dockerfile here seems outdated: https://hub.docker.com/r/mpioperator/kubectl-delivery/dockerfile

**Comment by rongou** [comment]
Ok I fixed the build. It's a configuration issue on dockerhub.

As for the failure, perhaps we shouldn't use distroless in this case as the main thing the container is doing is to copy a file.
