### ISSUE TITLE
does mpi-operator use podGroup resource

### ISSUE THREAD

**Issue by lvcaiping** [kubeflow/mpi-operator#265]
the function syncHandler  create podgroup resource .but i do not found the resource usge? what the role of this resource

**Comment by lvcaiping** [comment]
i think if does not use kube-batch scheduler,  the podgroup resource has no effect

**Comment by carmark** [comment]
@lvcaiping You can enable batch scheduler with `--gang-scheduling`.

**Comment by lvcaiping** [comment]
> @lvcaiping You can enable batch scheduler with `--gang-scheduling`.
yes, i seen; but i have another question.  does mpi-operator can support kube-batch with change any code. just need to deploy the kube-batch scheduler  and  enable  batch scheduler with --gang-scheduling

**Comment by carmark** [comment]
yes, I suppose it should work with `--gang-scheduling=kube-batch`.

**Comment by tenzen-y** [comment]
It seems that this issue was resolved. If you have any questions, feel free to open new issues.

/close
