### ISSUE TITLE
Need to specify the retry times of the MPI Job

### ISSUE THREAD

**Issue by cheyang** [kubeflow/mpi-operator#27]
Current the launcher Job's backoffLimit is 6, and it can't be modified the by end user. I suggest that the end user should be able to modify it.

And I think it can be 0 by default.

**Comment by rongou** [comment]
Is there a compelling reason to set it to 0 by default? Seems like there could be transient errors that the MPI Job could recover from by retrying, rather than failing right away?

**Comment by cheyang** [comment]
Do you have any suggestions on the  default value. the `backofflimit` is 6 for Kubernetes job.

**Comment by rongou** [comment]
Would it be too bad to leave the default as 6?
