### ISSUE TITLE
does the mpijob use ssh protocol communicate between launcher and worker ?

### ISSUE THREAD

**Issue by lvcaiping** [kubeflow/mpi-operator#270]

**Comment by lvcaiping** [comment]
i found the horovod dockerfile install ssh，but i not found it used in mpi-oprator code

**Comment by everpeace** [comment]
Basically, they are communicating with `kubectl exec` command.  mpi operator creates

- a configmap containing a script which does `kubectl exec`: https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/v1/mpi_job_controller.go#L1003-L1011
- set `OMPI_MCA_plm_rsh_agent` env var which refers to the script path: https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/v1alpha2/mpi_job_controller.go#L1256-L1259
- `kubectl` binary will be installed automatically into your pods by initContainer: https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/v1alpha2/mpi_job_controller.go#L1214-L1250 


So, you won't need to have `ssh` in your docker image at all.

**Comment by lvcaiping** [comment]
@everpeace thanks， i have another question，the kubelet exec  mpirun -np <>  ,
in distribute scene, does the np  means  worknum or slot num ？

**Comment by terrytangyuan** [comment]
@lvcaiping Please refer to mpirun's documentation here: https://www.open-mpi.org/doc/v4.0/man1/mpirun.1.php
