### ISSUE TITLE
slots in hostfile need to be configurable

### ISSUE THREAD

**Issue by cheyang** [kubeflow/mpi-operator#29]
The slots of the mpi-operator is not configurable. The current implementation is https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/mpi_job_controller.go#L753-#L761.  And the sample output is

```
cat /etc/mpi/hostfile
caffe-wd-mpijob-worker-0 slots=8 max_slots=8
caffe-wd-mpijob-worker-1 slots=8 max_slots=8
```

Please check `slots` and `max_slots` in https://www.ibm.com/support/knowledgecenter/en/SSZTET_10.1.0/smpi02/smpi02_host_list.html. I think we may have two choices:

1. Make slots configurable. Default setting are what we have.

2. Don't specify `slots` and `max_slots` in hostfile. Just leave it as `slots`  is 1 and `max_slots` as infinite. 

@rongou what's your thought?

**Comment by rongou** [comment]
Right now the slots are tied to the number of GPUs. Open MPI actually relies on the number of slots to figure out how many processes to launch. Is there a reason to change this behavior?

**Comment by cheyang** [comment]
Yes.
1. I think MPI operator can be used for scientific computing without GPU. If there is no GPU env, the slots should be the number of available processors on that host. The max slots being 1 is not acceptable.

2. For sharable GPU cases, some of our customers need to run more than one process in the same GPU  for MPI training. They can limit the GPU memory usage in application level.

So we have to make the `slots` configurable so they have freedom to change it.

**Comment by rongou** [comment]
The number of slots need to match the number of GPUs (or CPU cores if we want to support that), and then you can oversubscribe to launch more processes. See https://www.open-mpi.org/faq/?category=running#oversubscribing.

We can potentially not specify `max_slots` to allow oversubscribing, but messing with `slots` is not a good idea.

**Comment by rongou** [comment]
Sounds good.

**Comment by cheyang** [comment]
Will you make this change? @rongou , thanks.
