### ISSUE TITLE
slotPerWorker attribute and number of worker per node

### ISSUE THREAD

**Issue by kpouget** [kubeflow/mpi-operator#291]
Hello, I am confused by the meaning of the `slotPerWorker` [attribute](https://github.com/kubeflow/mpi-operator/blob/master/pkg/apis/kubeflow/v1alpha2/types.go):
```
type MPIJobSpec struct {

	// Specifies the number of slots per worker used in hostfile.
	// Defaults to 1.
	// +optional
	SlotsPerWorker *int32 `json:"slotsPerWorker,omitempty"`
        ...
}
```
Does worker refers to worker pods or worker nodes?

I would like to deploy 1 MPI job per worker *node*, but it seems to to be what the MPI operator does:
![multiple worker pods on one worker node](http://people.redhat.com/~kpouget/20-09-21/mpi_same_node.png)
(MPI worker pods `...-worker-0` and `...-worker-1` are both on the node `worker05`)

Is this a bug, or is there a way to deploy one pod per node?

**Comment by carmark** [comment]
Hello @kpouget ,

The `slotsPerWorker` comes from MPI's slots, you may ref it at [here](https://www.open-mpi.org/faq/?category=running#slots-without-hostfiles).

The `Worker` means worker pod, you can setup it in yaml file. You may use pod non-affinity feature to schedule them.

**Comment by kpouget** [comment]
Hello @carmark, 

> The `Worker` means worker pod, you can setup it in yaml file. 

I'm not sure to agree/observe what you're saying:

![mpi slots and pods](https://people.redhat.com/~kpouget/20-09-25/mpi-slots.png)

I request `4` replicas and `2` slots per worker, but I get 4 worker pods

**Comment by carmark** [comment]
@kpouget The replicas number is same as worker number. It will get 4 worker  pods if you request 4 worker replicas.

The slots will not impact the the number of worker pods, it will only be setup in mpi hostfile(/etc/mpi/hostfile).

**Comment by tenzen-y** [comment]
It seems that this was resolved. If you have any questions, feel free to open new issues.
/close
