### ISSUE TITLE
upgrade client-go to v0.18.3+

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubeflow/mpi-operator#323]
Current client-go version is old. Context.Context was introduced in client-go from v0.18.3 which breaks the old code.

**Comment by gaocegege** [comment]
We need to update volcano and many corresponding deps to use 0.18.

Maybe we could wait until https://github.com/volcano-sh/volcano/issues/1270 is fixed.

**Comment by snirkop89** [comment]
I'm having troubles using the typed client with the same reason of this issue.
Client:
`"github.com/kubeflow/mpi-operator/pkg/client/clientset/versioned/typed/kubeflow/v1"`
 getting error:
 `../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:72:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("mpijobs").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:89:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("mpijobs").VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:106:8: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("mpijobs").VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Watch
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:116:5: not enough arguments in call to c.client.Post().Namespace(c.ns).Resource("mpijobs").Body(mPIJob).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:129:5: not enough arguments in call to c.client.Put().Namespace(c.ns).Resource("mpijobs").Name(mPIJob.ObjectMeta.Name).Body(mPIJob).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:145:5: not enough arguments in call to c.client.Put().Namespace(c.ns).Resource("mpijobs").Name(mPIJob.ObjectMeta.Name).SubResource("status").Body(mPIJob).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:157:5: not enough arguments in call to c.client.Delete().Namespace(c.ns).Resource("mpijobs").Name(name).Body(options).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:173:5: not enough arguments in call to c.client.Delete().Namespace(c.ns).Resource("mpijobs").VersionedParams(&listOptions, scheme.ParameterCodec).Timeout(timeout).Body(options).Do
        have ()
        want (context.Context)
../../../../go/pkg/mod/github.com/kubeflow/mpi-operator@v0.3.0/pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/mpijob.go:186:5: not enough arguments in call to c.client.Patch(pt).Namespace(c.ns).Resource("mpijobs").SubResource(subresources...).Name(name).Body(data).Do
        have ()
        want (context.Context)`

go.mod:
`require (
	github.com/fatih/color v1.9.0
	github.com/jedib0t/go-pretty/v6 v6.2.4
	github.com/kubeflow/mpi-operator v0.3.0
	github.com/spf13/cobra v1.2.1
	github.com/spf13/viper v1.9.0
	k8s.io/api v0.20.2
	k8s.io/apimachinery v0.20.2
	k8s.io/client-go v12.0.0+incompatible
	kubevirt.io/client-go v0.47.1
)

require (
	github.com/PuerkitoBio/purell v1.1.1 // indirect
	github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 // indirect
	github.com/coreos/prometheus-operator v0.35.0 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c // indirect
	github.com/emicklei/go-restful v2.10.0+incompatible // indirect
	github.com/fsnotify/fsnotify v1.5.1 // indirect
	github.com/go-kit/kit v0.9.0 // indirect
	github.com/go-logfmt/logfmt v0.4.0 // indirect
	github.com/go-logr/logr v0.3.0 // indirect
	github.com/go-openapi/jsonpointer v0.19.3 // indirect
	github.com/go-openapi/jsonreference v0.19.3 // indirect
	github.com/go-openapi/spec v0.19.3 // indirect
	github.com/go-openapi/swag v0.19.5 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
	github.com/golang/mock v1.6.0 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/go-cmp v0.5.6 // indirect
	github.com/google/gofuzz v1.1.0 // indirect
	github.com/google/uuid v1.1.2 // indirect
	github.com/googleapis/gnostic v0.5.1 // indirect
	github.com/gorilla/websocket v1.4.2 // indirect
	github.com/hashicorp/golang-lru v0.5.4 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/imdario/mergo v0.3.10 // indirect
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/json-iterator/go v1.1.11 // indirect
	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111 // indirect
	github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515 // indirect
	github.com/kr/pretty v0.2.1 // indirect
	github.com/kubeflow/common v0.3.3 // indirect
	github.com/kubernetes-csi/external-snapshotter/v2 v2.1.1 // indirect
	github.com/magiconair/properties v1.8.5 // indirect
	github.com/mailru/easyjson v0.7.0 // indirect
	github.com/mattn/go-colorable v0.1.8 // indirect
	github.com/mattn/go-isatty v0.0.12 // indirect
	github.com/mattn/go-runewidth v0.0.9 // indirect
	github.com/mitchellh/mapstructure v1.4.2 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.1 // indirect
	github.com/openshift/api v3.9.1-0.20190401220125-3a6077f1f910+incompatible // indirect
	github.com/openshift/client-go v0.0.0 // indirect
	github.com/openshift/custom-resource-status v0.0.0-20200602122900-c002fd1547ca // indirect
	github.com/pborman/uuid v1.2.0 // indirect
	github.com/pelletier/go-toml v1.9.4 // indirect
	github.com/spf13/afero v1.6.0 // indirect
	github.com/spf13/cast v1.4.1 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.2.0 // indirect
	golang.org/x/crypto v0.0.0-20210817164053-32db794688a5 // indirect
	golang.org/x/net v0.0.0-20211015210444-4f30a5c0130f // indirect
	golang.org/x/oauth2 v0.0.0-20210819190943-2bc19b11175f // indirect
	golang.org/x/sys v0.0.0-20211019181941-9d821ace8654 // indirect
	golang.org/x/term v0.0.0-20201126162022-7de9c90e9dd1 // indirect
	golang.org/x/text v0.3.7 // indirect
	golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/ini.v1 v1.63.2 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
	k8s.io/apiextensions-apiserver v0.20.2 // indirect
	k8s.io/klog/v2 v2.4.0 // indirect
	k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd // indirect
	k8s.io/utils v0.0.0-20210111153108-fddb29f9d009 // indirect
	kubevirt.io/containerized-data-importer v1.36.0 // indirect
	kubevirt.io/controller-lifecycle-operator-sdk v0.2.1 // indirect
	sigs.k8s.io/structured-merge-diff/v4 v4.0.2 // indirect
	sigs.k8s.io/yaml v1.2.0 // indirect
)`

or am I doing something wrong?
