### ISSUE TITLE
[feature] Remove launcherRunsWorkload flag

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/mpi-operator#329]
Now we have a flag to determine that if we should use GPU in the launcher. 

But it is not expected in our situation. If we mount a GPU card to the launcher but the flag is disabled, we cannot see this card because we will set NVIDIA_VISIBLE_DEVICES to empty and libnvidia-container will not mount drivers to the pod.

We can remove the flag and rely on the launcher.resources.gpu to determine it.

**Comment by terrytangyuan** [comment]
Do you mean this PR? https://github.com/kubeflow/mpi-operator/pull/276

If we can determine it automatically then I am fine with it. 

cc @allenzfan

**Comment by Garrybest** [comment]
I will take it.

**Comment by fanzhe328** [comment]
@Garrybest  good！

**Comment by allenzfan** [comment]
@Garrybest good!

**Comment by gaocegege** [comment]
> If we can determine it automatically then yes.

Yeah, we can check if the launcher has GPUs.
