### ISSUE TITLE
running arbitrary OpenMPI jobs 

### ISSUE THREAD

**Issue by ahmet-uyar** [kubeflow/mpi-operator#351]
I have read in the MPI-Operator proposal document that running [arbitrary MPI jobs](https://github.com/kubeflow/community/blob/master/proposals/mpi-operator-proposal.md) listed as non-goals.  
I was wondering whether running arbitrary MPI jobs is currently supported. If so, is there any examples or documentation for that. 
thanks,

**Comment by terrytangyuan** [comment]
@rongou Do you remember the background on that non-goal item?

**Comment by rongou** [comment]
My initial goal was to get this working with Horovod. It may be possible to run other MPI jobs, I just didn't have the expertise or time/resource to support those. If anyone is interested in testing them out and adding documentation and examples, you are certainly welcome.

**Comment by ahmet-uyar** [comment]
@terrytangyuan  @rongou thank you for the quick reply. It was not clear to me whether MPI-Operator is only for all-reduce or for all MPI communications. From these messages I understand that full OpenMPI is installed in the worker container and arbitrary MPI jobs should run OK. Not sure whether I will have the time to test it but if I can, I will let you guys know.
