### ISSUE TITLE
strings.TrimeLeft issue prevents mpi-operator from deleting worker pods with index 2

### ISSUE THREAD

**Issue by zw0610** [kubeflow/mpi-operator#352]
go version: go version go1.13.15 darwin/amd64
mpi-operator version: v1

Users report that when scaling down worker replicas from 3 to 2, worker pod with trailing index "-2" is not deleted. I was able to reproduce this issue.

After dive into the code, I found this line: https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/v1/mpi_job_controller.go#L838

The `strings.TrimeLeft` returns empty string ("") for such the pod name (with trailing string "-2"). Here is a simplified debug code:

```golang
package main

import (
	"fmt"
	"strings"
)

func main() {
	prefix := "tensorflow2-keras-mnist-elastic-worker-"
	indices := []int{0, 1, 2, 3}
	for _, idx := range indices {
		s := fmt.Sprintf("%s%d", prefix, idx)
		left := strings.TrimLeft(s, prefix)
		fmt.Printf("%s = %s + \"%s\"\n", s, prefix, left)
	}
}
```

Here is the output:

```shell
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/lucas/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/ly/pt9gj22s5ggcfp32jy0vqs100000gn/T/___go_build_trimlefttest trimlefttest #gosetup
/private/var/folders/ly/pt9gj22s5ggcfp32jy0vqs100000gn/T/___go_build_trimlefttest
tensorflow2-keras-mnist-elastic-worker-0 = tensorflow2-keras-mnist-elastic-worker- + "0"
tensorflow2-keras-mnist-elastic-worker-1 = tensorflow2-keras-mnist-elastic-worker- + "1"
tensorflow2-keras-mnist-elastic-worker-2 = tensorflow2-keras-mnist-elastic-worker- + ""
tensorflow2-keras-mnist-elastic-worker-3 = tensorflow2-keras-mnist-elastic-worker- + "3"

Process finished with exit code 0

```

@terrytangyuan @gaocegege

**Comment by terrytangyuan** [comment]
Great found. Would you like to submit a PR to fix this?

**Comment by zw0610** [comment]
sure. just filed a pr mimicking how tf-operator maps pod to its index.
