### ISSUE TITLE
Launcher Init Container not being re-executed when worker node is drained

### ISSUE THREAD

**Issue by aalugore-ai** [kubeflow/mpi-operator#356]
Hi! I'm working with a slightly customized version of the mpi-operator. The new feature is pretty much to have the kubectl-delivery init container add some configuration files to the worker that are necessary for model training. I am attempting to do some chaos engineering by draining the worker node during training and then have the launcher reschedule the job to a different node. It mostly works, but I have discovered that the kubectl-delivery init container is not being re executed (kubectl describe node shows it only happens once in the events). Training fails due to a mismatch between the config files in the worker container. So I'm wondering how to force the kubectl-delivery init container to be re executed as part of the rebalancing sequence when the node a worker pod is on is drained.

**Comment by zw0610** [comment]
> the kubectl-delivery init container is not being re executed (kubectl describe node shows it only happens once in the events)

I believe this is how ['init'Container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) is designed.

It looks you need updated information about which worker Pods are still running. If so, please checkout the latest version of mpi-operator (still in master branch), where we have introduced a dynamically updated script `/etc/mpi/discover_hosts.sh`. It may not fit in your case out-of-box but can be tailored/modified.

In a more general way, you may consider add a [sidecar container](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar) to the launcher pod and use it to update the config files after node draining.

**Comment by aalugore-ai** [comment]
It seemed as though setting the launcher's restartPolicy to Never worked as a workaround as instead of restarting, a new launcher was made which re ran the init container.
