### ISSUE TITLE
Reevaluate: launcher can also run the workload

### ISSUE THREAD

**Issue by alculquicondor** [kubeflow/mpi-operator#393]
Context:
- Making the launcher also run the workload was initially proposed in #197 and implemented in #276 and #363
- I'm trying to ensure that the API is well defined

Paraphrased from https://github.com/kubeflow/mpi-operator/issues/197#issuecomment-867040347:

In my opinion, having the workload run in the launcher is ambiguous. Sometimes you have N workers (where N is the number specified in the worker replicas) and sometimes you have N+1. This is decided by just having a request for a resource that has "gpu" as a substring, which might have collisions with other user-defined requests.

Another potential problem is that users don't have fine control of how much of the requests/limits should go to the launcher process and how much to the workload process running in the same container.

If the idea is to be able to run a worker in the same node as the launcher, this can still be achieved by scheduling 2 pods on it (one for the worker and one for the launcher), setting the requests appropriately. Such behavior is more explicit from an API perspective. This setup also allows users who don't use GPUs to a workload in the same node as the launcher.

Alternatively, we could have an explicit field `.spec.runWorkloadInLauncher` or `.spec.LauncherPolicy`. But I believe good documentation around proper requests should be enough. Administrators could enforce that launchers don't requests GPUs in a webhook.

**Comment by alculquicondor** [comment]
cc @gaocegege @xychu @terrytangyuan @ahg-g

**Comment by gaocegege** [comment]
cc @carmark

**Comment by carmark** [comment]
We do not have CPU node in our GPU cluster, so the launcher will be better to run workload as same as others.

**Comment by alculquicondor** [comment]
> We do not have CPU node in our GPU cluster, so the launcher will be better to run workload as same as others.

What if set the launcher Pod with 0 requests so that it can land in the same Node as a worker? That should give you the behavior you want.

**Comment by alculquicondor** [comment]
ping @carmark @terrytangyuan

**Comment by carmark** [comment]
OK, SGTM
