### ISSUE TITLE
Launcher service account is always overwritten 

### ISSUE THREAD

**Issue by Dimss** [kubeflow/mpi-operator#394]
There is no way to use existing RBAC configurations (`ServiceAccount`, `Role` and `RoleBinding`) for `Launcher` containers. 
The MPIJob spec includes K8s pod template, where end user may configure desired `ServiceAccountName`
This configuration works as expected with `Worker` spec, but not with `Launcher` spec. 

For example, configuring `spec.mpiReplicaSpecs.Worker.template.spec.serviceAccountName=cnvrg` will cause all the workers pods to run with `cnvrg` service account.
However configuring `spec.mpiReplicaSpecs.Launcher.template.spec.serviceAccountName=cnvrg` **will not cause** all the launcher pods to turn with `cnvrg` service account, instead MPI Operator will  override this configuration, and will create a new `ServiceAccount`, `Role` and `RoleBinding` dedicated for the current MPIJob object, and the name of the objects will be `mpiJob.Name + launcherSuffix`

**Comment by alculquicondor** [comment]
@Dimss consider trying the v2 controller, which doesn't depend on ServiceAccounts :)

**Comment by Dimss** [comment]
@alculquicondor two questions 
1. is v2 controller is production grade? 
2. is v2 controller is serving same CRD spec as `v1alpha2`

**Comment by alculquicondor** [comment]
1. I'm working towards it. So far it has more coverage that the previous versions. But no-one is using it in production AFAIK.
2. No, I'm taking the chance to work towards a consistent API. It would be ideal to have a conversion webhook, but I might not have time for it. I would appreciate if someone else can take that lead, though.

**Comment by Dimss** [comment]
@alculquicondor thank you for your response. 
So, in that case, I'll have to continue to use `v1alpha2`, and hopefully my PR (#395) will be approved.

**Comment by alculquicondor** [comment]
I'd appreciate if you still have a chance to try the v2 controller. You can follow along with the progress in #373

**Comment by alculquicondor** [comment]
btw @Dimss: the v2 controller is now released as v0.3.0.
