### ISSUE TITLE
comment and code are inconsistent

### ISSUE THREAD

**Issue by HeGaoYuan** [kubeflow/mpi-operator#396]
Hi, kubeflow/mpi-operator team
    I read your code, and found that this comment/code is confusing. 
    https://github.com/kubeflow/mpi-operator/blob/990bf1c39dc641c65f9f56f2e9d2fbf1d9c31a81/pkg/controllers/v1/mpi_job_controller_status.go#L121-L124
    The comment says "Do not update lastTransitionTime if the status of the condition doesn't change.", but the code's action is "update lastTransitionTime if the status of the condition doesn't change"
    Looking forward to your reply.

**Comment by alculquicondor** [comment]
It is copying the `LastTransitionTime` from the existing condition into the new condition. That is inline with the comment.

**Comment by HeGaoYuan** [comment]
> It is copying the `LastTransitionTime` from the existing condition into the new condition. That is inline with the comment.

@alculquicondor Thanks for your reply. I am sorry that I was wrong.
