### ISSUE TITLE
move docker images to shared dockerhub or gcp

### ISSUE THREAD

**Issue by rongou** [kubeflow/mpi-operator#4]
Right now using my personal account for docker images. Should move to https://hub.docker.com/r/kubeflow/ or some shared place on gcp.

**Comment by gaocegege** [comment]
@jlewi Could you please guide rongou to push images to docker hub?

**Comment by jlewi** [comment]
Instructions about building docker images are here:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

The general process is create an argo workflow to build the images using docker in docker and then add the workflow to our nightly builds. 

We don't push to DockerHub regularly yet.

**Comment by rongou** [comment]
@jlewi do you know who owns the kubeflow org on docker hub? Can I be added to it? I set up dockerhub's automated build on my fork, seems to work well enough for top-of-tree images. We may still want to rely on argo to build nightlies and releases.

https://hub.docker.com/r/rongou/mpi-operator/
https://hub.docker.com/r/rongou/mpi-operator-kubectl-delivery/
https://hub.docker.com/r/rongou/mpi-operator-tensorflow-benchmarks/

**Comment by rongou** [comment]
BTW this is their documentation:

https://docs.docker.com/docker-hub/builds/
