### ISSUE TITLE
is the restartPolicy of pod can be set in MPIJob spec by user?

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#42]
I found that if i set `restartPolicy: Never` in `MPIJob` spec.

After create this mpijob , the restartPolicy  of `launcher` pod still is `OnFailure`

**Comment by rongou** [comment]
Yes right now it's hard-coded to `OnFailure`: https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/mpi_job_controller.go#L1040

We can potentially change it to match the user request if it's either `Never` or `OnFailure`, but default to `OnFailure` if it's not set. What do you think?

**Comment by tingweiwu** [comment]
@rongou That's nice If you can change like this.

**Comment by tingweiwu** [comment]
@rongou is this images `mpioperator/mpi-operator:laster` is auto rebuild after you change this?

**Comment by rongou** [comment]
@tingweiwu yes.
