### ISSUE TITLE
Update mpi-operator docs for 1.4

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/mpi-operator#423]
Can someone help update docs for 1.4 base on mpi release plan?

Doc: https://www.kubeflow.org/docs/components/training/mpi/
Umbrella issue: https://github.com/kubeflow/website/issues/2915

/cc @terrytangyuan @zw0610 @alculquicondor

**Comment by alculquicondor** [comment]
@terrytangyuan I thought the new operator wouldn't be included in kubeflow 1.4
