### ISSUE TITLE
tensorflow-bencharmark worker Authentication refused: bad ownership or modes for directory /root/.ssh 

### ISSUE THREAD

**Issue by crispto** [kubeflow/mpi-operator#424]
I'm new to kubefow, and I'm trying to run  a exmaple job in /examples/v1/tensorflow-benchmarks.yaml, but the launcher crashed after a few minutes and the working is still running. Logs show something like this is ORTE problem.
Some more infomation
 logs of the launcher, the launcher disappeared afater a few minutes while the workers are still running 

`root@localhost v1]# kubectl logs tensorflow-benchmarks-launcher-h58r5
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
Permission denied, please try again.
Permission denied, please try again.
root@tensorflow-benchmarks-worker-1.tensorflow-benchmarks-worker: Permission denied (publickey,password).
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   tensorflow-benchmarks-launcher
  target node:  tensorflow-benchmarks-worker-0.tensorflow-benchmarks-worker

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.`
2.  Environments
 os: CentOS Linux release 7.4.1708 (Core) 

docker version

`root@localhost v1]# docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:49 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 nvidia:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

kubernetes version

`Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

By the way,  knative-serving   activator is in status CrashLoopBackOff,  kubectl descibe shows the activator container is error, I am still debuging it, if it matters

When I run /example/tensorflow-benchmarks-imagenet.yaml I got 

`ssh: Could not resolve hostname tensorflow-benchmarks-imagenet-worker-1.tensorflow-benchmarks-imagenet-worker: Temporary failure in name resolution
ssh: Could not resolve hostname tensorflow-benchmarks-imagenet-worker-0.tensorflow-benchmarks-imagenet-worker: Temporary failure in name resolution`

Looks like svc error 

[root@localhost v1]# kubectl get svc
NAME                                    TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes                              ClusterIP   10.96.0.1    <none>        443/TCP   8d
tensorflow-benchmarks-imagenet-worker   ClusterIP   None         <none>        <none>    2m

**Comment by alculquicondor** [comment]
I apologize, I forgot to upload the new image for the tensorflow benchmarks that is compatible with the new version. I just uploaded it and did a successful run of `examples/v1/tensorflow-benchmarks.yaml`.

I think the failure you are seeing for the imagenet might be because the workers don't fit in your cluster (note that the workers request 8 GPUs). The way kubernetes works is that it would only setup networking once the workers are running. Since they are not, the launcher can't resolve them.

**Comment by crispto** [comment]
Thank you for your reply. I have pull the lated code and run examples/v1/tensorflow-benchmarks.yaml , but still get the error. The workers  are  running, while the launcher can not access them , looks like some ssh authentication problem. 

root@localhost v1# kubectl get po 
NAME                                                READY   STATUS             RESTARTS   AGE
nfs-client-nfs-client-provisioner-98c466959-g85gl   1/1     Running            4          8d
tensorflow-benchmarks-launcher-jxrqw                0/1     CrashLoopBackOff   3          4m53s
tensorflow-benchmarks-worker-0                      1/1     Running            0          4m53s
tensorflow-benchmarks-worker-1                      1/1     Running            0          4m53s

# logs of the launcher 
root@localhost v1# kubectl logs tensorflow-benchmarks-launcher-jxrqw
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
Permission denied, please try again.
Permission denied, please try again.
root@tensorflow-benchmarks-worker-0.tensorflow-benchmarks-worker: Permission denied (publickey,password).

#logs of the worker-0
[root@localhost v1]# kubectl logs tensorflow-benchmarks-worker-0
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Authentication refused: bad ownership or modes for directory /root/.ssh
Failed password for root from 172.100.1.217 port 39326 ssh2
Failed password for root from 172.100.1.217 port 39326 ssh2
Connection closed by authenticating user root 172.100.1.217 port 39326 [preauth]
Authentication refused: bad ownership or modes for directory /root/.ssh
Connection reset by authenticating user root 172.100.1.217 port 39882 [preauth]
Authentication refused: bad ownership or modes for directory /root/.ssh
Failed password for root from 172.100.1.217 port 40678 ssh2
Failed password for root from 172.100.1.217 port 40678 ssh2
Connection closed by authenticating user root 172.100.1.217 port 40678 [preauth]
Authentication refused: bad ownership or modes for directory /root/.ssh
Failed password for root from 172.100.1.217 port 41652 ssh2
Failed password for root from 172.100.1.217 port 41652 ssh2
Connection closed by authenticating user root 172.100.1.217 port 41652 [preauth]
Authentication refused: bad ownership or modes for directory /root/.ssh
Failed password for root from 172.100.1.217 port 43490 ssh2
Failed password for root from 172.100.1.217 port 43490 ssh2
Connection closed by authenticating user root 172.100.1.217 port 43490 [preauth]
Connection closed by 172.100.1.217 port 45642 [preauth]

**Comment by alculquicondor** [comment]
From the master branch, I just ran in a brand new cluster:

```
kubectl apply -f deploy/v2beta1/mpi-operator.yaml
kubectl apply -f examples/v1/tensorflow-benchmarks.yaml
```

And it worked normally. Note that the latest image has the following configuration: https://github.com/kubeflow/mpi-operator/blob/master/examples/tensorflow-benchmarks/Dockerfile#L3-L7
This should disable the file permission checks and disable writing the known hosts (because `/root/.ssh` is indeed read-only in mpi-operator).
So I have the feeling that you are still trying to run the old image.

The image ID for `mpioperator/tensorflow-benchmarks:latest` is `840932631c4c`.

If errors persist, please post the output of `kubectl get -o yaml pod` for the launcher and one of the workers.

**Comment by crispto** [comment]
you got it ,  though I don't know why docker pull didn't get me the latest clone.  I  build a new image from Dockerfile and the error disappeared! ,  Thanks!

**Comment by alculquicondor** [comment]
Awesome

/close

**Comment by celiawa** [comment]
Hi @alculquicondor, I have below error for the launcher pod.  Could you please help to have a look.

```
$ kubectl -n mynamespace exec -it tensorflow-benchmarks-launcher-62t7l sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "tensorflow-benchmarks" out of: tensorflow-benchmarks, istio-proxy, istio-init (init)
error: unable to upgrade connection: container not found ("tensorflow-benchmarks")
[epwiann@node-10-210-152-99 kubeflow]$ k turing001 -n ping-wang logs tensorflow-benchmarks-launcher-62t7l
Using deprecated annotation `kubectl.kubernetes.io/default-logs-container` in pod/tensorflow-benchmarks-launcher-62t7l. Please use `kubectl.kubernetes.io/default-container` instead
Warning: Permanently added 'tensorflow-benchmarks-worker-1.tensorflow-benchmarks-worker,10.42.138.147' (ECDSA) to the list of known hosts.
Warning: Permanently added 'tensorflow-benchmarks-worker-0.tensorflow-benchmarks-worker,10.42.91.237' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0640 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
Permission denied, please try again.
Permission denied, please try again.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0640 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
root@tensorflow-benchmarks-worker-1.tensorflow-benchmarks-worker: Permission denied (publickey,password).
Permission denied, please try again.
Permission denied, please try again.
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
root@tensorflow-benchmarks-worker-0.tensorflow-benchmarks-worker: Permission denied (publickey,password).
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   tensorflow-benchmarks-launcher
  target node:  tensorflow-benchmarks-worker-0.tensorflow-benchmarks-worker

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
```
```
$ kubectl get po -n mynamespace |grep benchmar
tensorflow-benchmarks-launcher-62t7l               1/2     CrashLoopBackOff   5          4m34s
tensorflow-benchmarks-worker-0                     2/2     Running            0          4m35s
tensorflow-benchmarks-worker-1                     2/2     Running            0          4m35s
```

My mpioperator/tensorflow-benchmarks is below, "2 weeks ago" much new.

```
# docker images|grep  tensorflow
mpioperator/tensorflow-benchmarks                                                  latest                           840932631c4c        2 weeks ago         9.72GB
```

And I've checked that in this tensorflow-benchmarks image, It have the following configuration: https://github.com/kubeflow/mpi-operator/blob/master/examples/tensorflow-benchmarks/Dockerfile#L3-L7 

```
$ k turing001 -n ping-wang exec -it tensorflow-benchmarks-worker-0 sh
# ls -al
total 12
drwxr-sr-x 2 root 1337 100 Sep 29 06:27 .
drwxrwsrwt 3 root 1337 140 Sep 29 06:27 ..
-rw-r----- 1 root 1337 253 Sep 29 06:27 authorized_keys
-rw-r----- 1 root 1337 365 Sep 29 06:27 id_rsa
-rw-r----- 1 root 1337 253 Sep 29 06:27 id_rsa.pub
#
#
#
#
#cat /etc/ssh/ssh_config

# This is the ssh client system-wide configuration file.  See
# ssh_config(5) for more information.  This file provides defaults for
# users, and the values can be changed in per-user configuration files
# or on the command line.

# Configuration data is parsed as follows:
#  1. command line options
#  2. user-specific file
#  3. system-wide file
# Any configuration value is only changed the first time it is set.
# Thus, host-specific definitions should be at the beginning of the
# configuration file, and defaults at the end.

# Site-wide defaults for some commonly used options.  For a comprehensive
# list of available options, their meanings and defaults, please see the
# ssh_config(5) man page.

Host *
#   ForwardAgent no
#   ForwardX11 no
#   ForwardX11Trusted yes
#   PasswordAuthentication yes
#   HostbasedAuthentication no
#   GSSAPIAuthentication no
#   GSSAPIDelegateCredentials no
#   GSSAPIKeyExchange no
#   GSSAPITrustDNS no
#   BatchMode no
#   CheckHostIP yes
#   AddressFamily any
#   ConnectTimeout 0
#   IdentityFile ~/.ssh/id_rsa
#   IdentityFile ~/.ssh/id_dsa
#   IdentityFile ~/.ssh/id_ecdsa
#   IdentityFile ~/.ssh/id_ed25519
#   Port 22
#   Protocol 2
#   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
#   MACs hmac-md5,hmac-sha1,umac-64@openssh.com
#   EscapeChar ~
#   Tunnel no
#   TunnelDevice any:any
#   PermitLocalCommand no
#   VisualHostKey no
#   ProxyCommand ssh -q -W %h:%p gateway.example.com
#   RekeyLimit 1G 1h
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
```

**Comment by alculquicondor** [comment]
This log line:

> Permissions 0640 for '/root/.ssh/id_rsa' are too open.

Implies that somehow this didn't run:

https://github.com/kubeflow/mpi-operator/blob/c5c0c3ef99ec9de948600766988ea7134d3d2af6/v2/pkg/controller/mpi_job_controller.go#L1526

Can you show the output of `kubectl -o yaml pod tensorflow-benchmarks-launcher-62t7l`? I wonder if the volumes were setup correctly.

**Comment by alculquicondor** [comment]
I just run the sample using mpi-operator:0.3.0, /deploy/v1beta2/mpi-operator.yaml and /examples/v1/tensorflow-benchmarks.yaml from the master branch and couldn't reproduce the issue

**Comment by alculquicondor** [comment]
I'll stop answering here in favor of #429
