### ISSUE TITLE
Conditionally create the launcher Service for Intel

### ISSUE THREAD

**Issue by alculquicondor** [kubeflow/mpi-operator#426]
If you are not familiar with Intel MPI, by default workers communicate back to the launcher using its hostname. In the operator, we use a headless Service so the launcher hostname gets a DNS record.

However, I recently learned that there is a way to avoid a launcher Service when creating Intel MPI jobs. If you specify the `-iface` flag with the network interface, the IP is used instead. You can also use the `I_MPI_HYDRA_IFACE` env variable.

However, I don't think it's realistic for the mpi-operator to be able to deduce the interface name and set it for users. But if the users know it (it probably is `eth0` in most cases) and pass it through the env variable, maybe we can provide the option to:

- skip the service creation
- skip the launcher dns resolution check in the entry point.

Is the API reasonable (include the env variable in the pod spec) or should we create a dedicated field in the API?

**Comment by alculquicondor** [comment]
cc @terrytangyuan @ahg-g

**Comment by ahg-g** [comment]
>   If you specify the -iface flag with the network interface, the IP is used instead.

You mean the launcher will communicate its IP to the workers so they use it when connecting back?

In general, specifying the interface name is quite strange. Other than the issue of hostnetworking, which I think we can workaround, what is the disadvantage of continuing to create a headless service for the launcher?

**Comment by alculquicondor** [comment]
> You mean the launcher will communicate its IP to the workers so they use it when connecting back?

Correct.

> Other than the issue of hostnetworking, which I think we can workaround

Actually, if the launcher uses the node hostname, I think the workers should be able to resolve it. At least they do in GKE.

> what is the disadvantage of continuing to create a headless service for the launcher?

It's just one more DNS entry we need to wait for to be ready. But perhaps the effect is negligible in a big Job. So, very low priority.

**Comment by terrytangyuan** [comment]
It's no big deal to create a headless service for launcher for me. You can give very minimal resources if that's the concern.

**Comment by ahg-g** [comment]
Services don't require "giving" resources.

**Comment by alculquicondor** [comment]
It doesn't seem like getting rid of the Service would provide a valuable difference to users.

Perhaps we can re-evaluate if Intel MPI handles failures and retries better so that we can completely get rid of the entry point. That would make it equivalent to the infrastructure for Open MPI.

/close
