### ISSUE TITLE
v0.2.3 deployment manifest incorrectly refers to latest tag on mpi-operator image

### ISSUE THREAD

**Issue by thoraxe** [kubeflow/mpi-operator#437]
https://github.com/kubeflow/mpi-operator/blob/v0.2.3/deploy/v1alpha2/mpi-operator.yaml

The deployment for the operator pod is using the `latest` tag. Unfortunately, the `latest` build of the operator image no longer supports `kubectl-delivery-image` as an option/flag.

The `mpi-operator.yaml` needs to refer to the matching tag string. In this case, `v0.2.3`'s manifest should refer to `mpioperator/mpi-operator:v0.2.3`

**Comment by alculquicondor** [comment]
Can you please send a PR for this? I'm happy to review.

**Comment by thoraxe** [comment]
@alculquicondor yes and no. I can send a PR with `v0.2.3` tags, but I'm not sure what your NVRC policy is, so technically any PR should result in a `v0.2.4` tag being created, and that's a bit of a chicken-egg problem.

If you're going to version image releases along with repo tags, it might make more sense to use `kustomize` to handle the deployment to ensure the correct tag(s)... ?

**Comment by alculquicondor** [comment]
I'm not sure if a new version is planned (cc @terrytangyuan)

but at least you can fix it for master.

**Comment by thoraxe** [comment]
@alculquicondor I cannot fix it for master, because `master` *SHOULD* point to `latest`. There's nothing to PR for master. Unless you are referring to _removing_ the flag from the deployment that's no longer supported by the operator. But that's not what this issue is about.

**Comment by alculquicondor** [comment]
Ah, that's a fair point. The problem is that we always release from master, instead of doing branch cuts.

In any case, anything preventing you from upgrading to 0.3.0?

**Comment by thoraxe** [comment]
I was told there were issues running 0.3.0 on OpenShift. I'll give 0.3.0 a whirl and see what happens. I'm trying to run OpenFOAM OpenMPI jobs so I've got a bunch of pre-work to do to get to a point where it might work.

**Comment by alculquicondor** [comment]
Yeah, there is some prework on the images. They require some particular SSH configuration. You can have a look at them here:
- https://github.com/kubeflow/mpi-operator/blob/master/examples/base/Dockerfile
- https://github.com/kubeflow/mpi-operator/blob/master/examples/tensorflow-benchmarks/Dockerfile

**Comment by alculquicondor** [comment]
But you can always upgrade to 0.3.0 and use the old controller this way:
- https://github.com/kubeflow/mpi-operator/blob/8943cf734da77ea0445b4ee2afd3927240b5a2d5/deploy/v1/mpi-operator.yaml#L192
- https://github.com/kubeflow/mpi-operator/blob/8943cf734da77ea0445b4ee2afd3927240b5a2d5/deploy/v1alpha2/mpi-operator.yaml#L199

But I strongly encourage you to use the newer operator (v2, the default)

**Comment by thoraxe** [comment]
It's not clear to me how SSH is used. The `tensorflow-benchmark` image is based on the `horovod` image. While the latter has some SSH libraries installed, it does not appear to actually run or start SSHD. The [blog post](https://medium.com/kubeflow/introduction-to-kubeflow-mpi-operator-and-industry-adoption-296d5f2e6edc) mentions:

> A helper shell script that can be used by mpirun in place of ssh. It invokes kubectl exec for remote execution.

But it is not clear what causes the `mpi-operator` to use that script.

But this is not related to the bug.

**Comment by alculquicondor** [comment]
We got rid of kubectl exec in 0.3.0 in favor of SSH, as it was not a scalable solution.

**Comment by tenzen-y** [comment]
The v1 MPIJob was deprecated and removed from this repository a year ago.
Hence, I would recommend migrating to v2beta1

/close
