### ISSUE TITLE
Uploading image on docker hub

### ISSUE THREAD

**Issue by gajanankulkarni-18** [kubeflow/mpi-operator#442]
Hi,
There is no image available for ppc64le of mpi-operator.
we will create the image but can you please provide the mechanism to upload the image on docker hub

**Comment by terrytangyuan** [comment]
Perhaps it's more maintainable to just keep the Dockerfiles in the repo so that others can build the images themselves.

**Comment by tenzen-y** [comment]
This was fixed.

https://hub.docker.com/r/mpioperator/mpi-operator/tags
/close
