### ISSUE TITLE
Elastic resize broken in v2 operator: Horovod requires the slots parameter

### ISSUE THREAD

**Issue by alculquicondor** [kubeflow/mpi-operator#445]
In the v2 controller, the slots parameter in the hostfile was replaced by environment variables:

https://github.com/kubeflow/mpi-operator/blob/b88edad03a4b55708deaed5f8ebe058eeacf19bd/v2/pkg/controller/mpi_job_controller.go#L116-L117

However, horovod still requires the number of slots. So we need to put the parameter back. The duplication of information should be fine.
It's unclear if horovod supports intel.

We need an E2E test to ensure that the fix works long term.

**Comment by alculquicondor** [comment]
Also, we need to adapt the intel entry point to the change of the hostfile format: https://github.com/kubeflow/mpi-operator/blob/master/examples/base/intel-entrypoint.sh

**Comment by alculquicondor** [comment]
@tenzen-y we should fix this as part of the next release #507, but I don't have bandwidth. Do you?

**Comment by tenzen-y** [comment]
> @tenzen-y we should fix this as part of the next release #507, but I don't have bandwidth. Do you?

@alculquicondor Thanks for mentioning this. Sure.

IIUC, we need to modify the hostfile in https://github.com/kubeflow/mpi-operator/blob/31d4575066770756cc8ca347cc6d5ba3113b1e02/pkg/controller/mpi_job_controller.go#L1186
to `buffer.WriteString(fmt.Sprintf("%s%s-%d.%s slots=%d\n", mpiJob.Name, workerSuffix, i, workersService, slots))`, right? 

Also, we need to adapt the new hostfile format in https://github.com/kubeflow/mpi-operator/blob/db6930dcd509b1d97a47bcccd1bcb1da5eaea712/examples/base/intel-entrypoint.sh#L30.
