### ISSUE TITLE
MPI Operator - namespace scope 

### ISSUE THREAD

**Issue by talcoh2x** [kubeflow/mpi-operator#450]
Hi, there is an option to run MPI operator cross namespaces?

**Comment by alculquicondor** [comment]
I think this was discussed here: #449

Not sure what the solution was, but you could ask that contributor. And if you could document the steps in the README or in a sample yaml, that would be helpful for future users.

**Comment by zw0610** [comment]
If you wish to let mpi-operator to watch MPIJobs across multiple namespaces, you can either just omit the launch argument `--namespace` and it will use turn to [default mode](https://github.com/kubeflow/mpi-operator/blob/master/cmd/mpi-operator.v1/app/options/options.go#L57), which is to monitor MPIJobs across all namespace unless environment variable `KUBEFLOW_NAMESPACE ` is set.
