### ISSUE TITLE
[Feature request] Add namespace and `svc` suffix for host configmap

### ISSUE THREAD

**Issue by shaowei-su** [kubeflow/mpi-operator#453]
In the v2 implementation, headless worker service is referenced by `jobname-worker-0.jobname-worker` (https://github.com/alculquicondor/mpi-operator/blob/master/v2/pkg/controller/mpi_job_controller.go#L1110)  which requires the pod `/etc/resolv.conf` config having `namespace.svc.cluster.local` presented.

The `tf-operator` on the other side composes TFCONFIG with both namespace and `svc` suffix: https://github.com/kubeflow/training-operator/blob/master/pkg/controller.v1/tensorflow/tensorflow.go#L159

Is it possible to consolidate the logic so that the same cluster DNS settings work for both operators?

**Comment by alculquicondor** [comment]
Isn't `namespace.svc.cluster.local` already added by kubelet?

In any case, I think it should all continue to work seamlessly if we add `namespace.svc`

**Comment by shaowei-su** [comment]
Not always the case depends on network level configs set up. I validated that adding `namespace.svc` works well like you mentioned.

**Comment by alculquicondor** [comment]
Feel free to send a PR

**Comment by shaowei-su** [comment]
PTAL https://github.com/kubeflow/mpi-operator/pull/454

**Comment by alculquicondor** [comment]
Fixed in #454 
/close
