### ISSUE TITLE
Is there a way to have each worker print its index in the logs?

### ISSUE THREAD

**Issue by jzfb2** [kubeflow/mpi-operator#462]
Does MPI-Operator jobs have a parameter allowing each worker to print it's index?

**Comment by zw0610** [comment]
I believe the hostname of each worker contains the index information. So maybe just use `echo` + `hostname` + `awk`.
If the hostname does not work, you can set an environment variable as [downard api](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) from the Pod name (`metadata.name`).

But if the real information you would like to have is the `Rank`, please be aware that the index does not equal to the rank in every case.

**Comment by jzfb2** [comment]
Ya, I'm terrible with jargon, I believe the correct term is rank. So in the case of a job with 2 nodes and 3 slots, I should see values 0 to 5.

So from the launcher pod logs what I'm expecting from 2 worker nodes with a single slot each is....
0: entry 1
1: entry 1
1: entry 2
0: entry 2
....
0: entry N
1: entry N

I currently am accomplishing this with a python script that runs the payload as a subprocess and uses environment variables to obtain the rank. However I was asked to find a solution that doesn't involve needing to add additional files to the container. Does such a thing exist?

**Comment by alculquicondor** [comment]
Any reason why you can't use https://www.open-mpi.org/doc/v4.0/man3/MPI_Comm_rank.3.php ?

**Comment by jzfb2** [comment]
The issue isn't knowing rank, the issue is having each entry line print {rank}: {log entry}. I already know the environment variable for rank. @zw0610, I'm not familiar with how awk can resolve this issue. If you could elaborate on it, that would be appreciated.

**Comment by alculquicondor** [comment]
Do you want the rank in the MPI world or the "index" that mpi-operator assigns to each worker pod that it creates?

**Comment by jzfb2** [comment]
So I have the rank, it's $OMPI_COMM_WORLD_RANK, but I don't know a command line way to do `#: log entry` via command line. With SLURM it just does it without issue(I didn't create the setup for SLURM), but I'm trying to do the same with K8S.

**Comment by jzfb2** [comment]
So what I thought was produced by SLURM turns out to be a product of mpirun. What I was looking for was the flag `--tag-output`.
