### ISSUE TITLE
MPI Operator failing continuously

### ISSUE THREAD

**Issue by SachinT95** [kubeflow/mpi-operator#469]
I'm trying to install the kubeflow setup on my azure cluster but the MPI operator is failing due to "CrashLoopBackOff".

![image](https://user-images.githubusercontent.com/88109806/178187637-e8d2fa2f-5de0-459d-a52e-1b8f931ad30b.png)

Can any help me with the solution? what could be the root cause for the above error?
It is able to pull the image but not able to run the container.
![image](https://user-images.githubusercontent.com/88109806/178187175-bc2ef203-d269-4c31-b83a-e5376b091a98.png)

**Comment by alculquicondor** [comment]
You need to provide way more information than that :)

Which version of the operator are you running?

Can you gather the logs from the pods (driver and workers)?

**Comment by SachinT95** [comment]
Hey @alculquicondor, Thanks for responding 

I'm using "**mpioperator/mpi-operator:latest**" i.e. version > 0.3.0.
please find the csv file which contains pods log
[query_data.csv](https://github.com/kubeflow/mpi-operator/files/9092442/query_data.csv)

Please let me know if you need more details.

**Comment by alculquicondor** [comment]
`"7/12/2022, 11:30:42.000 AM",flag provided but not defined: -kubectl-delivery-image`

I think you are trying to use the new container image with old manifests.

Have you tried with these? https://github.com/kubeflow/mpi-operator/blob/master/deploy/v2beta1/mpi-operator.yaml

**Comment by SachinT95** [comment]
Hey @alculquicondor, sorry for my late reply.

Should I replace current yaml file with  https://github.com/kubeflow/mpi-operator/blob/master/deploy/v2beta1/mpi-operator.yaml this one? or do I need to replace specific parameter from the ymal file?

**Comment by alculquicondor** [comment]
I would suggest replacing it.

**Comment by SachinT95** [comment]
Thanks @alculquicondor for your help
