### ISSUE TITLE
I have a problem about the code, worker config command sleep 365d, how the laucher wake up the worker

### ISSUE THREAD

**Issue by xqqcoder** [kubeflow/mpi-operator#47]

**Comment by rongou** [comment]
The launcher invokes `mpirun` which uses `kubectl exec` to remotely execute the desired commands on the worker pods. When `mpirun` finishes, the operator/controller sets the number of replicas to 0 for the worker statefulset. There is more information in the original proposal: https://github.com/kubeflow/community/blob/master/proposals/mpi-operator-proposal.md

**Comment by xqqcoder** [comment]
thank you, I got it

**Comment by xqqcoder** [comment]
thank you, i got it
