### ISSUE TITLE
launcher pod displays `Init:ImagePullBackOff`, and it failed to pull `mpioperator/kubectl-delivery:latest`

### ISSUE THREAD

**Issue by thuzhf** [kubeflow/mpi-operator#471]
When I apply a mpi related yaml, it shows:

![image](https://user-images.githubusercontent.com/8064242/185613054-6e602ac5-7edc-481b-9da4-c5820aee2089.png)

![image](https://user-images.githubusercontent.com/8064242/185613007-a3f799c8-b4b6-4a0b-84a7-6f77a43acac0.png)

But as the doc shows, v2 drops the kubectl-delivery image requirement.
Is this a bug? How can I solve this problem? I hope at least I can edit the kubectl-delivery image registry because I am using intranet in my company and cannot connect to Internet. All I can use is a private registry for docker images.

**Comment by terrytangyuan** [comment]
You can push the images to your own Docker registry and use those instead.

**Comment by alculquicondor** [comment]
What is your yaml?

And how did you upgrade the mpioperator to v2?

**Comment by thuzhf** [comment]
> You can push the images to your own Docker registry and use those instead.

But I cannot change the image url. For example, the image url in our registry is: `myregistry.com/path1/kubectl-delivery:latest`. But there's no where for me to change to this url in mpi-operator's yaml. I use the following method to install v2 version of mpi-operator (refer to: https://github.com/kubeflow/mpi-operator#installation):
```
git clone https://github.com/kubeflow/mpi-operator
cd mpi-operator
kubectl apply -f deploy/v2beta1/mpi-operator.yaml
```

> What is your yaml?

My yaml will be updated here later.

> And how did you upgrade the mpioperator to v2?

Please see the first reply. I just follow the readme in this github repo.

**Comment by alculquicondor** [comment]
Is it possible that the error is from an MPIJob that existed before the upgrade?

v2 is not backwards compatible, so you need to deploy your job again, following the new API https://github.com/kubeflow/mpi-operator/blob/master/examples/v2beta1/tensorflow-benchmarks/tensorflow-benchmarks.yaml

**Comment by thuzhf** [comment]
> Is it possible that the error is from an MPIJob that existed before the upgrade?
> 
> v2 is not backwards compatible, so you need to deploy your job again, following the new API https://github.com/kubeflow/mpi-operator/blob/master/examples/v2beta1/tensorflow-benchmarks/tensorflow-benchmarks.yaml

That may be possible. I will try `kubectl delete -f deploy/v2beta1/mpi-operator.yaml` and `kubectl delete -f deploy/v1/mpi-operator.yaml` to delete all related resources to avoid using any v1 resources and reinstall v2 version to see if it works.

**Comment by thuzhf** [comment]
I tried the above method, but it still didn't work. My yaml is as follows:
![image](https://user-images.githubusercontent.com/8064242/185830408-e856caf4-3b8e-4768-84b7-79c79446110b.png)

And the result is as follows:
`kubectl get pods`
![image](https://user-images.githubusercontent.com/8064242/185830509-ca31a65b-dcbb-473d-a983-e06b77356726.png)

`kubectl describe pods simple-mpi-launcher`

![image](https://user-images.githubusercontent.com/8064242/185830747-06a11738-91a6-44be-8582-f0682ce50184.png)

**Comment by thuzhf** [comment]
I have a few questions:
1. I doubt whether I am using v2 version only when I install it via `kubectl apply -f deploy/v2beta1/mpi-operator.yaml`. It seems there are some v1 resources in `deploy/v2beta1/mpi-operator.yaml`?
2. In v2, how does launcher send commands to workers? Via `ssh` or `kubectl`? It seems in v1, it is via `kubectl`. In v2, is it `ssh`?

**Comment by alculquicondor** [comment]
The v2beta1 operator still adds the CRDs for v1, but it operates entirely with v2beta1 APIs. The image also comes with the v1 operator, but it should run the v2 operator by default.

What is the output of `kubectl get -o yaml -n mpi-operator deployment mpi-operator`?

v2 uses ssh. So everything you are showing points that you are somehow running the v1 operator instead.

**Comment by thuzhf** [comment]
> What is the output of `kubectl get -o yaml -n mpi-operator deployment mpi-operator`?
> 

![image](https://user-images.githubusercontent.com/8064242/185933520-b50692d3-3486-45b7-a3e6-3fc4c519b16b.png)

**Comment by alculquicondor** [comment]
I just installed mpi-operator in my cluster from https://hub.docker.com/r/mpioperator/mpi-operator and run this example https://github.com/kubeflow/mpi-operator/blob/master/examples/v2beta1/pi/pi.yaml and it worked.

Is it possible that your image is outdated?

You can also try adding this to the Deployment:

```yaml
- command: ["/opt/mpi-operator.v2"]
```

To be sure that the v2 operator is running.

**Comment by thuzhf** [comment]
OK. I'll try to add this command.

**Comment by thuzhf** [comment]
@alculquicondor Unfortunately, it doesn't work...it still uses `kubectl-delivery` image. Something must be wrong with `deploy/v2beta1/mpi-operator.yaml`...

![image](https://user-images.githubusercontent.com/8064242/185975150-c8f01fee-b5c8-4c56-bbd1-7031c16d09d3.png)
![image](https://user-images.githubusercontent.com/8064242/185975246-c2706ae1-eae2-4bba-a8a7-ce5d1a86b0d7.png)

**Comment by thuzhf** [comment]
And when I comment all `v1alpha2` and `v1` parts from `deploy/v2beta1/mpi-operator.yaml` and apply this yaml, and rerun my mpijob, it works like a magic...
![image](https://user-images.githubusercontent.com/8064242/185975954-df294783-3cec-4067-97ce-25d620a5dec4.png)

**Comment by alculquicondor** [comment]
That is very odd. I kind of looks like both operators were running.
I just noticed now that in all the screenshots you shared you have two launcher pods. The launcher pods from v2 should always have a `-randomstring` at the end. The ones from v1 didn't have this suffix.

Now, removing the old APIs shouldn't affect the fact that 2 operators are running. However, the old operator would now be crashing, because it's APIs don't exist anymore.

Is it possible that you have a rogue mpi-operator v1 running in a different deployment?

**Comment by thuzhf** [comment]
Where can I find the old operator (if it exists)? I can only find one pod running in namespace `mpi-operator`.

**Comment by alculquicondor** [comment]
No idea. Do you also have kubeflow installed separately?

**Comment by thuzhf** [comment]
> No idea. Do you also have kubeflow installed separately?

Yes. I installed some parts of kubeflow about a year ago. And it includes mpi-operator and training-operator. But the  mpi-operator will not be deleted by `kubectl delete -f deploy/v2beta1/mpi-operator.yaml` and `kubectl delete -f deploy/v1/mpi-operator.yaml`? I have executed these commands multiple times before I do `kubectl apply -f deploy/v2beta1/mpi-operator.yaml`.

**Comment by alculquicondor** [comment]
No, because the mpi-operator packaged with kubeflow is in the kubeflow namespace. Check the documentation for kubeflow on how to disable a specific component (including in the training operator). I'm not familiar enough with it to give you more clear instructions.

/close

**Comment by thuzhf** [comment]
> No, because the mpi-operator packaged with kubeflow is in the kubeflow namespace. Check the documentation for kubeflow on how to disable a specific component (including in the training operator). I'm not familiar enough with it to give you more clear instructions.
> 
> /close

I just found the evil `mpi-operator` pod in kubeflow namespace. Holy crap...
