### ISSUE TITLE
How can I use a different scheduler from volcano?

### ISSUE THREAD

**Issue by thuzhf** [kubeflow/mpi-operator#474]
I want to use other scheduler (my own scheduler and etc). How can I configure mpi-operator to use other scheduler (like changing some parameter)?

**Comment by alculquicondor** [comment]
You can set the `schedulerName` within the Pod templates of your MPIJobs.

There is this command line flag https://github.com/kubeflow/mpi-operator/blob/993b010e05c48c6f6ef5a5180362ccd3e716982e/v2/cmd/mpi-operator/app/options/options.go#L65, however, it assumes that you want to use Volcano's PodGroup API, even if using a different scheduler.

There are also these open issues https://github.com/kubeflow/training-operator/issues/1519 to integrate with queuing systems instead. But I don't think anybody is working on them at the moment https://github.com/kubernetes-sigs/kueue/issues/65.

I would welcome contributions to mpi-operator and kueue, if you would like to contribute.

**Comment by thuzhf** [comment]
Thanks. I'll have a try.
And the `job-manager` introduced by `kueue` seems very promising. I've always wanted to have a `job-level` manager (argo is not) instead of `pod-level` manager and avoid duplicating mature functionality in k8s.
