### ISSUE TITLE
Launcher pod seems disabling GPU

### ISSUE THREAD

**Issue by o0fatigue** [kubeflow/mpi-operator#476]
Hello. I was trying to use GPUs in the launcher pod, because in my use case some non-mpi computing, which is prerequisite to my mpi program, should be done in the launcher before starting the mpi program. However, I found that in the launcher pod, GPUs are not available, and it seems due to the null environment variables of NVIDIA_VISIBLE_DEVICES and NVIDIA_DRIVER_CAPABILITIES set onto the launcher pod. I have the following questions:
1. I am pretty sure that these two environment variables are not set by my code nor configuration, so is this a behavior of mpi-operator itself?
2. If yes, what are the concerns of disabling GPU usage in the launcher pod?

Thank you.

**Comment by terrytangyuan** [comment]
It's by design. Launcher pod doesn't need GPUs.

**Comment by o0fatigue** [comment]
@terrytangyuan Thank you for your reply. However, if I really need GPU in launcher pod (for some computation not related to MPI as I mentioned), is there any possible method to enable GPU usage in launcher? And will there be any limitations or problems if I use GPUs in launcher pod?

**Comment by terrytangyuan** [comment]
You'll need to modify the source code yourself then.

**Comment by alculquicondor** [comment]
Here is where the variables are added https://github.com/kubeflow/mpi-operator/blob/master/v2/pkg/controller/mpi_job_controller.go#L1379

Have you tried running the code on an MPI rank instead? that should be equivalent.

**Comment by o0fatigue** [comment]
thank you guys! closing this issue
