### ISSUE TITLE
Remove mpi-operator v1 from this repository

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/mpi-operator#486]
/kind discussion

We unified mpi-operator v1 to training-operator in https://github.com/kubeflow/training-operator/pull/1457.
For now, we maintain mpi-operator v1 in a couple of repositories, and it is difficult to keep maintain both mpi-operator in perfect sync with specifications. Also, users are likely to be confused.

So, it might be better to remove mpi-operator v1 from this repository and move codes for the v2beta1 to the top of the directory.

@alculquicondor @terrytangyuan @gaocegege @zw0610 WDYT?

**Comment by terrytangyuan** [comment]
I don't think there is any new changes in v1. All changes to v1 has been frozen so it doesn't matter much whether to remove it from the repo.

**Comment by gaocegege** [comment]
LGTM

**Comment by alculquicondor** [comment]
+1 to removing the code for v1.

We could move the code as well, but we need to keep the name of the package as v2, similar to https://github.com/kubernetes/klog/blob/main/go.mod

**Comment by terrytangyuan** [comment]
@tenzen-y Would you like to submit a PR to remove it?

**Comment by tenzen-y** [comment]
@terrytangyuan Yes, I would like to take this.

/assign
