### ISSUE TITLE
Slow to start a MPIJob

### ISSUE THREAD

**Issue by answer3y** [kubeflow/mpi-operator#49]
My k8s has thousands of mpijob，when I create a new mpijob，it takes long time to be run.

I find that the code below:
`kubeflowInformerFactory := informers.NewSharedInformerFactory(kubeflowClient, time.Second*30)` in md/mpi-operator/main.go

Because of the implement of informer, the mpi-operator will check and sync the MPIJob status every 30 second. I have thousands of MPIJobs that make the new job to be run late.

After I set the second parament of NewSharedInformerFactory to be vary large for example  200000, the new job will be run at a quick time.

I just want to ask, is any  side effect  if I make this modify? 

Thank you very much

**Comment by rongou** [comment]
Thanks for the report! Searching around for this problem, there doesn't seem to be a definitive answer. In the kubernetes code base it's mostly set to minutes. Can you try something like `kubeflowInformerFactory := informers.NewSharedInformerFactory(kubeflowClient, 10*time.Minute)` to see if that solves your problem?

**Comment by rongou** [comment]
By the way I'm really interested in where you are running these thousands of mpi jobs and for what purpose. :) Can I quote you guys as a user/customer of mpi-operator?

**Comment by rongou** [comment]
Right, setting the resync period to 0 means to never resync, that should solve your problem.

**Comment by rongou** [comment]
@answer3y do you mind telling me your group/company's name? If you don't feel comfortable sharing it on github, you can email me directly (rong dot ou at gmail dot com), or hit me up on the kubeflow slack. Thanks!
