### ISSUE TITLE
Add suspend semantics

### ISSUE THREAD

**Issue by alculquicondor** [kubeflow/mpi-operator#504]
The semantics should be similar to that of k8s Job.

And this will pave the work for the training-operator (https://github.com/kubeflow/training-operator/issues/1519)

**Comment by mimowo** [comment]
@tenzen-y @alculquicondor you may want to look at the WIP implementation (tested manually) here: https://github.com/kubeflow/mpi-operator/pull/511. Any early feedback is welcome.

**Comment by tenzen-y** [comment]
Probably, we can close this issue.
