### ISSUE TITLE
Support the different GPU of pod in one job?

### ISSUE THREAD

**Issue by xieydd** [kubeflow/mpi-operator#52]
Are there any plans in place to meet this demand , if i have a job need 15 gpus, It is automatically allocated as to the shape of 2, 2, 5, and 6 depend on node resources.
@rongou

**Comment by rongou** [comment]
There is some support for this in the current implementation, but not to the extent that you want.

For performance reasons, it's better to run each pod on as many gpus as possible. For example, if you have 8-gpu nodes, you should launch 8-gpu worker pods. That way NCCL can leverage NVLink for higher bandwidth and lower latency within each node. Crossing the node boundary is expensive, even with InfiniBand or RoCE, so you should avoid it as much as possible.

In a large production cluster the nodes might get fragmented, making it hard to allocate many 8-gpu pods. If you want more scheduling flexibility at the cost of lower efficiency, you can set the `gpusPerNode` flag in the operator to a lower value (e.g. `4`) than your actual gpu count. At the extreme you can set it to `1` so you pods can run anywhere, but training would be pretty slow.

To get the kind of flexibility you want, the operator would need to understand the availability of gpus, which is probably not something it should be concerned about. I guess it could query the api server to find out, then reserve the gpus and configure the mpi job accordingly, but I'm not sure if it's worth the complexity. I think a better alternative is for the scheduler to do bin-packing on gpus, packing smaller jobs together, leaving more full nodes for multi-node jobs. Not sure if any of the current schedulers do this. Maybe you can look into it?

**Comment by xieydd** [comment]
I'm sorry, maybe I didn't make myself clear. When the task is decomposed, it is considered to occupy as many gpu resources as possible on a single node. If a single node does not have enough resources, it will be allocated to multiple nodes. The problem is that the current architecture of the mpi operator indicates that all pod gpus for a task are the same.

**Comment by rongou** [comment]
I guess I didn't make myself clear. :) Using the maximum number of gpus per node for each worker pod is the most efficient way to do multi-node training, so that's the default behavior. If your goal is to fully utilize all the gpus and reduce job queuing, it's best done by the scheduler bin-packing.

The exact mechanism you described seems rather imperative, goes against kubernetes' philosophy of declarative configuration.

**Comment by rongou** [comment]
I think this is outside the scope of the mpi operator. Closing for now.

**Comment by xieydd** [comment]
@rongou I have implemented the version of mpi-operator , but i did`t think this  conform to declarative logic, so i give up it.
