### ISSUE TITLE
Consider handling the minResources when using volcano as a gang scheduler

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/mpi-operator#535]
Since #520, the mpi-operator respects the `.spec.runPolicy.schedulingPolicy` when creating the PodGroup.
Currently, the mpi-operator just passes the `.spec.runPolicy.schedulingPolicy.minResources` to the `.spec.minResources` in PodGroup when using volcano as a gang scheduler.

However, we may want to calculate all required resources in Launcher and Workers considering priorityClasses and then pass it to `.spec.minResources` in PodGroup like the following:

https://github.com/kubeflow/mpi-operator/blob/2bc2b6500cd1f5e502b366ad8b529d9324bd63f2/pkg/controller/podgroup.go#L89-L168

/help

**Comment by alculquicondor** [comment]
To clarify, we are looking for help from folks that have experience with volcano.
