### ISSUE TITLE
separate out worker and launcher pod specs

### ISSUE THREAD

**Issue by rongou** [kubeflow/mpi-operator#54]
The worker pods and the launcher typically have very different resource requirements. Right now we have a single spec for them and the controller munges the launcher podspec to make it more resource efficient. We should give user more control by separating out the worker and launcher pod specs. Need to move the api version to v1alpha2.

See #53

**Comment by soyuutaku** [comment]
Is there any Road-map for v1alpha2? Separate out worker and launcher is necessarily. It may add possible to add some initial containers for workers but the launcher just need to trigger the job.

**Comment by terrytangyuan** [comment]
This is now fixed via `v1alpha2`.
