### ISSUE TITLE
Sometimes appear this problem

### ISSUE THREAD

**Issue by Chaos-Ju** [kubeflow/mpi-operator#55]
+ POD_NAME=tensorflow-benchmarks-16-custom-worker-0
+ shift
+ /opt/kube/kubectl exec tensorflow-benchmarks-16-custom-worker-0 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "633602048" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "tensorflow-benchmarks-16-custom-launcher-s96hl,tensorflow-benchmarks-16-custom-worker-0,tensorflow-benchmarks-16-custom-worker-1@0(3)" -mca orte_hnp_uri "633602048.0;tcp://192.168.201.141:33011" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
+ POD_NAME=tensorflow-benchmarks-16-custom-worker-1
+ shift
+ /opt/kube/kubectl exec tensorflow-benchmarks-16-custom-worker-1 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "633602048" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "tensorflow-benchmarks-16-custom-launcher-s96hl,tensorflow-benchmarks-16-custom-worker-0,tensorflow-benchmarks-16-custom-worker-1@0(3)" -mca orte_hnp_uri "633602048.0;tcp://192.168.201.141:33011" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
error: unable to upgrade connection: Unauthorized
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   tensorflow-benchmarks-16-custom-launcher-s96hl
  target node:  tensorflow-benchmarks-16-custom-worker-1

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the proble

**Comment by rongou** [comment]
Probably some network setup issue. Once the pods are up, you can try to talk to them manually:
```
kubectl exec tensorflow-benchmarks-16-custom-worker-1 -- hostname
kubectl exec tensorflow-benchmarks-16-custom-launcher-s96hl -- /opt/kube/kubectl exec tensorflow-benchmarks-16-custom-worker-1 hostname
```

**Comment by Chaos-Ju** [comment]
done
