### ISSUE TITLE
Seeing Launcher have two status: {'active': 1, 'failed': 1}

### ISSUE THREAD

**Issue by kkolli** [kubeflow/mpi-operator#552]
Hello - To determine when MPIJob is completed, we get the statuses of the MPIJob and look at the launcher status. 

If the launcher is `active`, we do nothing. 
If the launcher is `failed` or `succeeded`, we mark it completed and reflect the corresponding status. 
However, during testing, we are seeing this as the status of the MPIJob:
`{'Launcher': {'active': 1, 'failed': 1}, 'Worker': {'active': 1}}`

Can anyone confirm if this is by design or if its a bug? In the above status, we have the launcher as both `active` and `failed`.

**Comment by tenzen-y** [comment]
Hi, @kkolli.
Thanks for creating this issue.

That is a specification, not a bug.

The mpi-operator uses batch/job as a launcher. And then, the mpi-operator populate the failed count of batch/job to mpijob:

https://github.com/kubeflow/mpi-operator/blob/c034b8caf613b2951aa2550c32f1333c58f56a39/pkg/controller/mpi_job_controller.go#L997-L998

**Comment by alculquicondor** [comment]
"failed" refers to the past.
Your example can be interpreted as: one pod has failed, one is currently active.
