### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/mpi-operator#563]
I think we can release a new version once the following tasks are completed.

### Included in v0.5.0
- [x] https://github.com/kubeflow/mpi-operator/pull/561
- [x] https://github.com/kubeflow/mpi-operator/pull/562
- [x] https://github.com/kubeflow/mpi-operator/pull/484
- [x] https://github.com/kubeflow/mpi-operator/pull/564

### Not included in v0.5.0
- [ ] https://github.com/kubeflow/mpi-operator/issues/537
- [ ] https://github.com/kubeflow/mpi-operator/issues/565
- [ ] https://github.com/kubeflow/mpi-operator/issues/541

cc: @alculquicondor @terrytangyuan

**Comment by alculquicondor** [comment]
+1

**Comment by tenzen-y** [comment]
I added #564.

**Comment by terrytangyuan** [comment]
Sounds good

**Comment by tenzen-y** [comment]
I added https://github.com/kubeflow/mpi-operator/issues/565

**Comment by eero-t** [comment]
Any progress on this?   0.4.0 support is for quite old Kubernetes version, and currently even MPI-operator head is missing support for the latest 1.28 Kubernetes version.

**Comment by tenzen-y** [comment]
> Any progress on this? 0.4.0 support is for quite old Kubernetes version, and currently even MPI-operator head is missing support for the latest 1.28 Kubernetes version.

I haven't decided yet the exact date for the release. However, I'm hoping to release v0.5.0 in October later or November mid.

**Comment by bdevcich** [comment]
Any updates on this? Appreciate the work you do!

**Comment by tenzen-y** [comment]
> Any updates on this? Appreciate the work you do!

Not yet. I will share the new milestone within this month.

**Comment by tenzen-y** [comment]
We decided that some issues would be postponed until after the next release.

**Comment by tenzen-y** [comment]
Completed: https://github.com/kubeflow/mpi-operator/releases/tag/v0.5.0
/close
