### ISSUE TITLE
Copy APIs from common repo into here

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/mpi-operator#564]
We merged the common repo into the training operator. So we will archive the common repo.
Hence, coping APIs from common into here would be good.

ref: https://github.com/kubeflow/training-operator/pull/1813

**Comment by terrytangyuan** [comment]
That's fine. It would be good to leave a link to the source of truth in the comment

**Comment by tenzen-y** [comment]
> That's fine. It would be good to leave a link to the source of truth in the comment

Sounds good.
