### ISSUE TITLE
Add support for linux/arm64 for MPICH

### ISSUE THREAD

**Issue by sheevy** [kubeflow/mpi-operator#565]
Currently we support OpenMPI on amd64, arm64 and ppc64le, but Intel MPI and MPICH are only supported on amd64. It would be great if we had feature parity in that regard.

**Comment by tenzen-y** [comment]
/retitle Add support for linux/arm64 and linux/ppc64le for MPICH

**Comment by sheevy** [comment]
> If MPICH doesn't support other platforms, we can close this issue.

I think it supports both amd64 and ppc64le, e.g. see: https://koji.mbox.centos.org/koji/buildinfo?buildID=20381

**Comment by tenzen-y** [comment]
I confirmed the MPICH works on the linux/arm64 platform using [ytenzen/mpi-pi:test-mpich](https://hub.docker.com/layers/ytenzen/mpi-pi/test-mpich/images/sha256-b69020bddab3dfdb54974702d23f85373d792541d5016009c6daddb913000f48?context=repo).

```shell
$ kubectl get nodes --show-labels 
NAME                 STATUS   ROLES           AGE     VERSION   LABELS
kind-control-plane   Ready    control-plane   6m26s   v1.27.1   beta.kubernetes.io/arch=arm64,beta.kubernetes.io/os=linux,kubernetes.io/arch=arm64...
```

However, I can not confirm if the MPICH works on the linux/ppcle64 platform since I don't have the ppc64le environment.

**Comment by tenzen-y** [comment]
> > However, I can not confirm if the MPICH works on the linux/ppcle64 platform since I don't have the ppc64le environment.
> 
> As this is marked for release 0.5.0, maybe ARM is enough for that and PPC support can be split to a separate ticket / to come later ?

I agree. If you can verify the ppc64le, let me know the result.

**Comment by tenzen-y** [comment]
As you can see here (https://hub.docker.com/r/mpioperator/mpich-builder/tags), we have already been supported the linux/arm64 arch for the MPICH.

So, closing this issue and creating the ppc64le supporting issue separately.

**Comment by tenzen-y** [comment]
Opened: https://github.com/kubeflow/mpi-operator/issues/660
