### ISSUE TITLE
Add integration and e2e test for the volcano integration

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/mpi-operator#568]
Both integration and e2e tests for the volcano don't exist, although the mpi-operator has a volcano integration feature.
So we should add integration and e2e test for the volcano, similar to scheduler-plugins.

We are looking for contributors that are familiar with volcano.

For scheduler-plugins, we have the following tests:

- integration test
https://github.com/kubeflow/mpi-operator/blob/21f326d1d2e5f1beed667da0cc61e1d07158ef0c/test/integration/mpi_job_controller_test.go#L466-L474

- e2e test
https://github.com/kubeflow/mpi-operator/blob/21f326d1d2e5f1beed667da0cc61e1d07158ef0c/test/e2e/mpi_job_test.go#L306-L309

/help

**Comment by tenzen-y** [comment]
@lowang-bh Can you take this issue?

**Comment by lowang-bh** [comment]
> @lowang-bh Can you take this issue?

ok, give me some time. 

/assign

**Comment by tenzen-y** [comment]
> > @lowang-bh Can you take this issue?
> 
> ok, give me some time.
> 
> /assign

Thanks!
/remove-help
