### ISSUE TITLE
Expected ssh contract that must be followed by images to use this operator

### ISSUE THREAD

**Issue by aavbsouza** [kubeflow/mpi-operator#580]
Hello. Is there a formal contract or documentation about the needs of this operator with respect ssh communication on the setup phase of one distributed job. For instance here (https://github.com/kubeflow/mpi-operator/tree/master/build/base) is built some images that are able to communicate without root, with ssh. For a custom docker  image what would be the expectation?

thanks

**Comment by tenzen-y** [comment]
Actually, there aren't any docs for the custom images.
But you can copy from https://github.com/kubeflow/mpi-operator/blob/18250f5e6980ce3afbf86359f8aa5fa9ac6cf831/build/base/Dockerfile#L3-L31 to your Dockerfile.

Then, you can add your custom setting. Actually, in my env, the solution works well, although I use `nvcr.io/nvidia/pytorch:23.05-py3` as a base image.

**Comment by tenzen-y** [comment]
If you have any other questions, feel free to re-open this issue.
/close
