### ISSUE TITLE
Connection dropped after 24 hours

### ISSUE THREAD

**Issue by sheevy** [kubeflow/mpi-operator#581]
My MPI Job died surprising close to after 24 hours mark (twice already). The pod is still running, it's just the connections dropped:

```
Server listening on 0.0.0.0 port 2222.
Server listening on :: port 2222.
kex_exchange_identification: Connection closed by remote host
Connection closed by 111.111.111.111 port 49772
Accepted publickey for mpiuser from 111.111.111.111 port 34662 ssh2: ECDSA SHA256:****************************
kex_exchange_identification: Connection closed by remote host
Connection closed by 111.111.111.111 port 42110
kex_exchange_identification: Connection closed by remote host
```

I haven't touched sshd file or specify anything related to timout in MPI Job definition.

Can anyone think of why a job could die after 24 hours, or is it just a red herring and I should look for the problem elsewhere?

**Comment by alculquicondor** [comment]
I don't see how this could a problem in mpi-operator.

More likely it's something in the application. Have you checked the logs in the worker pod?

/close
