### ISSUE TITLE
Hard requirement on cluster-level roles

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/mpi-operator#59]
Current to deploy MPI-Operator, we have to apply cluster-level roles, e.g. `ClusterRole` and `ClusterRoleBinding` specified in [deploy/2-rbac.yaml](https://github.com/kubeflow/mpi-operator/blob/master/deploy/2-rbac.yaml). However, some infrastructure rules/restrictions that disallow such cluster-level roles. 

The cluster level roles seem needed even though the `MPIJob`, controller, etc. are in the same namespace, e.g. 
```
E1220 21:58:10.883867       1 reflector.go:205] github.com/kubeflow/mpi-operator/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Role: roles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:kube:mpi-operator" cannot list roles.rbac.authorization.k8s.io at the cluster scope
E1220 21:58:10.884831       1 reflector.go:205] github.com/kubeflow/mpi-operator/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:kube:mpi-operator" cannot list jobs.batch at the cluster scope
E1220 21:58:10.885790       1 reflector.go:205] github.com/kubeflow/mpi-operator/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:kube:mpi-operator" cannot list statefulsets.apps at the cluster scope
E1220 21:58:10.886972       1 reflector.go:205] github.com/kubeflow/mpi-operator/pkg/client/informers/externalversions/factory.go:62: Failed to list *v1alpha1.MPIJob: mpijobs.kubeflow.org is forbidden: User "system:serviceaccount:kube:mpi-operator" cannot list mpijobs.kubeflow.org at the cluster scope
```
This is because the current MPI Operator code lists everything at the cluster scope and we don't know which namespace `MPIJob` might be in. Changes are needed in the codebase in order to remove this hard requirement.

**Comment by terrytangyuan** [comment]
Thanks @rongou for re-opening this. #60 did not resolve this completely yet. There's still remaining issue:

```
E1224 01:25:30.194723       1 reflector.go:205] github.com/kubeflow/mpi-operator/pkg/client/informers/externalversions/factory.go:62: Failed to list *v1alpha1.MPIJob: mpijobs.kubeflow.org is forbidden: User "system:serviceaccount:kube:mpi-operator" cannot list mpijobs.kubeflow.org at the cluster scope
```
This is because we still need to do the same thing for `kubeflowInformerFactory`. However, it is using `github.com/kubeflow/mpi-operator/pkg/client/informers/externalversions` which is generated by `informer-gen` but `NewFilteredSharedInformerFactory` wasn’t generated automatically since we are using an old version of `k8s.io/code-generator`.

The upgrade of `k8s.io/code-generator` is blocked by this in `Gopkg.toml`:
```
[[constraint]]
  name = "k8s.io/code-generator"
  # We can not use master since the generated package name is changed from tensorflow to kubeflow.
  revision = "961bc077103364eb5bda2c40e2b560d068c9a8c6"
```

**Comment by rongou** [comment]
We can probably update the dependencies now.

**Comment by rongou** [comment]
Sent you #78.
