### ISSUE TITLE
which is the latest mpi job definition between mpi-operator and training operator 

### ISSUE THREAD

**Issue by sxwl-donggang** [kubeflow/mpi-operator#605]
I know the `training operator repo` has included the MPI Job type. Is the definition in mpi-operater different from the training operator. which one should i use?

**Comment by tenzen-y** [comment]
I would suggest using the mpi-operator since the training-operator supports only MPIJob v1, and the MPIJob v1 will be deprecated. Also, MPIJob v2 (provided only in the mpi-operator) has more scalability than MPIJob v1 (provided only in the training-operator).

**Comment by sxwl-donggang** [comment]
Understand, thank you!
