### ISSUE TITLE
how could  mpijob of mpi operator worker get the hostname of launcher

### ISSUE THREAD

**Issue by Oneal65** [kubeflow/mpi-operator#641]
I want to add a plug-in  in worker, so how could  mpijob of mpi operator worker get the hostname of launcher

such as: 
in the launcher etc/mpi/hostfile
pi-worker-0.pi.default.svc slots=1
pi-worker-1.pi.default.svc slots=1

**Comment by alculquicondor** [comment]
what kind of plugin are you referring to?

For now, only Intel and MPICH know the hostname of the launcher, because they need it. But in OpenMPI, workers don't generally need to know who the launcher is.

**Comment by Oneal65** [comment]
> what kind of plugin are you referring to?
> 
> For now, only Intel and MPICH know the hostname of the launcher, because they need it. But in OpenMPI, workers don't generally need to know who the launcher is.

Thanks for your reply. the plugin  in worker is used to send message to launcher by gprc or http but not mpi, it's used for other applications not for mpi program.
