### ISSUE TITLE
Add support for the managedBy field

### ISSUE THREAD

**Issue by mimowo** [kubeflow/mpi-operator#646]
### What you would like to be added?

The support for the `managedBy` field which can delegate reconciliation from built-in controller, to a custom one.

The semantics of the field are:
- whenever the value is set, and it does not point to the built-in operator, then skip reconciliation
- the field is immutable
- the field is not defaulted

### Why is this needed?

For context, we have in Kueue the effort (see [Support Kubeflow Jobs in MultiKueue](https://github.com/kubernetes-sigs/kueue/issues/2552)) to support kubeflow-training (it will include MPIJob), but it will not be complete without the support for managedBy.

The complete support for the users of [MultiKueue](https://kueue.sigs.k8s.io/docs/tasks/manage/setup_multikueue/) (multi-cluster Kueue) means:
- simpler installation (just follow the standard installation path), otherwise only installation of MPIJob CRDs is required
- support for mixed setup in one cluster - some MPIJob could be run by MultiKueue and some by the default operator

The efforts to support the field in:
- [k8s Job](https://github.com/kubernetes/enhancements/issues/4368) (alpha)
- [JobSet](https://github.com/kubernetes-sigs/jobset/issues/440) (complete)

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

**Comment by mimowo** [comment]
/cc @andreyvelich @tenzen-y 
Would you like to include this feature?

**Comment by mimowo** [comment]
xref for the similar issue in the training operator: https://github.com/kubeflow/training-operator/issues/2193

**Comment by tenzen-y** [comment]
As we discussed in kubeflow community meeting, basically, I'm with this feature.
But, I would like to know what @alculquicondor thinks since maybe I don't have enough bandwidth to review this feature.

**Comment by alculquicondor** [comment]
+1 to this feature.

I also can't promise review bandwidth, but it's something that needs to be done for consistency with the other APIs.

**Comment by tenzen-y** [comment]
@mszadkow Do you have any plans to work on this issue?
