### ISSUE TITLE
Next release date with updated k8s libraries for 1.31

### ISSUE THREAD

**Issue by klueska** [kubeflow/mpi-operator#652]
I'm curious if there is any new release planned soon?

I am particularly interested in a release that would bump the k8s libraries to 1.31 so that the PodSpecTemplate embedded in an MPIJob would include the latest DRA APIs.

**Comment by tenzen-y** [comment]
Thank you for creating this issue.
I'm wondering if we can cut a new release after https://github.com/kubeflow/mpi-operator/pull/650 is merged.

@alculquicondor After the k/k enhancement freeze, can you help with the release process?

**Comment by klueska** [comment]
I wouldn't close this until *after* the release goes out (not just the PR updating the libraries is merged). Can someone reopen it, please?

**Comment by klueska** [comment]
Thanks everyone for the quick turnaround on this. I can confirm that with the latest updates I am able to run MPIJobs that reference ResourceClaims using the k8s 1.31 DRA APIs.

**Comment by terrytangyuan** [comment]
Great!

**Comment by tenzen-y** [comment]
Thank you for letting us know! I'd be glad to see the possibility for the MPIJob with DRA!
