### ISSUE TITLE
Plans for mpi-operator in Kubeflow 0.5?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/mpi-operator#66]
What are the plans for the mpi-operator in 0.5?

/cc @everpeace @rongou

**Comment by rongou** [comment]
We are planning some work internally (at NVIDIA) to have better support for
gang scheduling, bare metal/networking performance etc. Not sure how what
would fit into the kubeflow release schedule. What's the target date for
0.5?

**Comment by k82cn** [comment]
@rongou , are going to have a new implementation of gang-scheduling or leveraging [kube-batch](https://github.com/kubernetes-sigs/kube-batch) ?

**Comment by rongou** [comment]
This work is mostly done by the Nvidia GPU Cloud (NGC) team. They have an internal scheduler, but they are also looking at kube-batch, so I guess it's still to be determined.

**Comment by k82cn** [comment]
Got that; if anything I can help, please let me now :)

**Comment by k82cn** [comment]
> They have an internal scheduler, 

BTW, if the scheduler is internal, how other use that?

**Comment by terrytangyuan** [comment]
Not sure if these will all fit in Kubeflow 0.5 but just want to add a couple related issues for discussion here:
* Additional tags for docker images on Dockerhub and formal release before any API changes: https://github.com/kubeflow/mpi-operator/issues/72
* Update `k8s.io/code-generator` as discussed in https://github.com/kubeflow/mpi-operator/issues/59
* [WIP] Support processing resource types other than GPU in https://github.com/kubeflow/mpi-operator/pull/75

**Comment by k82cn** [comment]
> they have plans to eventually open source it, but for now it's on NGC only.

Got that :)

**Comment by terrytangyuan** [comment]
@everpeace good to know that. Let's continue non-GPU specific discussion on the PR.

**Comment by rongou** [comment]
@cheyang see #54.

**Comment by cheyang** [comment]
Thanks, got it!
