### ISSUE TITLE
switch to operator sdk?

### ISSUE THREAD

**Issue by rongou** [kubeflow/mpi-operator#7]
Not sure how mature it is, but might want to switch the implementation to use the [operator sdk](https://github.com/operator-framework/operator-sdk).

**Comment by gaocegege** [comment]
Could you explain what we will get from the switch?

**Comment by rongou** [comment]
I think the main benefit is ease of maintenance, and maybe leverage other parts in the operator framework: https://coreos.com/blog/introducing-operator-framework.

**Comment by rongou** [comment]
Yeah probably not. :)
