### ISSUE TITLE
Additional tags for docker images on Dockerhub

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/mpi-operator#72]
Currently Docker images are being built and pushed automatically to [mpioperator on Dockerhub](https://hub.docker.com/u/mpioperator). However, the images built automatically do not have tags other than "latest". We can probably tag them with Git commit hashes and then have an official release tag. Otherwise, users will end up maintaining their own images and releases which is unaffordable in the long term.

**Comment by rongou** [comment]
Agreed. That was my quick and dirty solution. Kubeflow has a more formal release process and pushes docker images to GCP. Maybe it's something we can leverage?

**Comment by terrytangyuan** [comment]
Yes that would work. Alternatively, Travis seems to provide an easy process for this as well that we might want to consider: 
https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by rongou** [comment]
Got it configured on docker hub.
