### ISSUE TITLE
how does the shift command work in the kubexec configmap

### ISSUE THREAD

**Issue by EdwardZhang88** [kubeflow/mpi-operator#82]
I am doing a comparison test on a 3 node*4GPU setting which involves using both openMPI and mvapich. While the default openMPI is good to run, I have trouble in getting mvapich to work with mpi-operator. And I believe the problem is that mvapich fails to recognize the hostfile as the log shows only 3 shift happen(while it is 12 for openMpi), one for each pod.
Original hostfile:
pod1 slots=4
pod2 slots=4
pod3 slots=4
I then updated the hostfile to make it compatible with mvapich as below but still only 3 shift happen and the process just hangs there.
Updated hostfile
pod1:4
pod2:4
pod3:4
I have even tried this hostfile below but no luck.
Updated again hostfile
pod1
pod1
pod1
pod1
pod2
pod2
pod2
pod2
pod3
pod3
pod3
pod3

Here is the mpiexec command I am using.
`mpiexec -n 12 -launcher rsh -launcher-exec /etc/mpi/kubexec.sh -f /etc/mpi/hostfile -env <key> <value> ./script.sh` 
At this point, I am really wondering how does this [shift logic](https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/mpi_job_controller.go#L770) works under the hood. Does it take the hostname from hostfile and how does it that happen? Can you give some suggestion here?Thanks.@rongou

**Comment by EdwardZhang88** [comment]
Just have a closer look at the openMPI log, there are actually only 3 shift too. I was misled because mpirun has been triggered for both workers and servers.

**Comment by rongou** [comment]
The shift just takes off the pod name, then the rest of the args are passed to kubectl. Perhaps you can play around with this repo (https://github.com/rongou/k8s-openmpi) to debug this type of issues.

We haven't tested the operator on mvapich at all. If you get it working, feel free to send us PRs.

**Comment by EdwardZhang88** [comment]
Thanks for your reply. Right now I am trying with mvapich only because some training tasks get hung in the middle using current OpenMpi+kubectl exec approach while the same task runs smoothly using conventional mvapich+passwordless SSH. My question is do you think that kubeclt exec could be a potential I/O bottleneck since it flows the data load all the way from node a -> apiServer -> kubelet on node b -> node b?@rongou

**Comment by rongou** [comment]
Seems unlikely. `kubectl exec` is only used for the initial handshake, afterwards OpenMPI takes over and does its own networking.

**Comment by EdwardZhang88** [comment]
@rongou Yes, you are right. I confirm that kubectl exec as RSH launcher to initialize MPI is not an issue. It appears that openMPI may have some MCA related parameters (e.g., -mca btl_openib_receive_queues even though I didn't use openib in the first place) which require special tuning. I haven't really figured it out how and why. But I do manage to run my training task successfully without any hanging problem simply by replacing openMPI with pre-built mvapich2.2. To sum up, mvapich + kubectl exec does work in my case. Thanks for your help.
