### ISSUE TITLE
MPI job needs rich status information

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/mpi-operator#88]
Could we add `startTime` and `completionTime` field in the status?  `launcherStatus` is helpful on status but can not indicate job duration. 

```
{
"startTime": "2019-02-08T22:19:09Z"
"launcherStatus": "Succeeded"
"completionTime": "2019-02-08T22:19:47Z",
}

```

I can open a PR for this issue if you think it's reasonable.

**Comment by rongou** [comment]
Sure, feel free to send a PR.

**Comment by Jeffwan** [comment]
Add #89

**Comment by Jeffwan** [comment]
PR merged and close the issue.
