### ISSUE TITLE
Continuous building docker images

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/mpi-operator#93]
I notice `mpioperator/mpi-operator:latest` is from `rongou/mpi-operator` which sometimes has delay.  

1. Could you help release latest mpi operator image? I'd like to use feature from latest version. I can use customized image for now and this is a low priority request. 

2. Does mpi-operator project has CI and CD support? It would be great to use latest image which consistent with upstream repo changes. I would also suggest to build stable tag along with kubeflow release. 

Reference: 
https://hub.docker.com/r/mpioperator/mpi-operator

**Comment by rongou** [comment]
The images are up to date, but we probably should use travis to build them. If anyone wants to take it on, I'd be happy to give you the permissions you need.

@terrytangyuan brought up this before.

**Comment by terrytangyuan** [comment]
@rongou Feel free to grant me the permission. We can probably have someone from our team to help with this.

**Comment by rongou** [comment]
@terrytangyuan I added you as an owner of the `mpioperator` org on docker hub. Let me know if you need anything else.

https://cloud.docker.com/u/mpioperator/orgs/mpioperator/teams

**Comment by terrytangyuan** [comment]
This is part of https://github.com/kubeflow/mpi-operator/issues/217. I plan to leverage Kubeflow's infra for this so I updated the title of this issue.

**Comment by carmark** [comment]
@terrytangyuan Shall we use `kubeflow` org on the docker hub? I am the owner of it, and I can add you in that org.

**Comment by terrytangyuan** [comment]
@carmark I was thinking publishing to gcp similar to other projects but feel free to add me to the org and my ID should be terrytangyuan.

**Comment by tenzen-y** [comment]
This was resolved. The operator image is uploaded to dockerhub every PR merge.
/close
